services:
  postgres:
    image: postgres:16-alpine
    container_name: meow-postgres
    environment:
      POSTGRES_USER: meow
      POSTGRES_PASSWORD: meowpass
      POSTGRES_DB: meow
    ports:
      - "5432:5432"
    volumes:
      - meow_pg:/var/lib/postgresql/data
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
      - ./migrations/002_social.sql:/docker-entrypoint-initdb.d/002_social.sql:ro
      - ./migrations/003_user_phone.sql:/docker-entrypoint-initdb.d/003_user_phone.sql:ro
      - ./migrations/004_notifications_actor_image.sql:/docker-entrypoint-initdb.d/004_notifications_actor_image.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meow -d meow"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: meow-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - meow_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  meow_pg:
  meow_redis:
