(function () {
  const THEME_KEY = "meow_theme";
  const LANG_KEY = "meow_lang";

  const SUPPORTED_THEMES = [
    { id: "light", label: { zh: "浅色", en: "Light", ja: "ライト" } },
    { id: "dark", label: { zh: "深色", en: "Dark", ja: "ダーク" } },
    { id: "warm", label: { zh: "暖橙", en: "Warm", ja: "ウォーム" } },
  ];

  const SUPPORTED_LANGS = [
    { id: "zh", label: "简体中文" },
    { id: "en", label: "English" },
    { id: "ja", label: "日本語" },
  ];

  const DICT = {
    zh: {
      "app.title": "喵友圈",
      "app.subtitle": "猫咪与宠物主人的分享与交易社区",
      "nav.docs": "系统文档",
      "nav.dashboard": "我的管理中心",
      "nav.home": "返回前台",
      "nav.login": "登录",
      "nav.register": "注册",
      "nav.logout": "退出",
      "nav.settings_theme": "主题",
      "nav.settings_lang": "语言",
      "auth.title": "登录 / 注册",
      "auth.tab_login": "登录",
      "auth.tab_register": "注册",
      "auth.placeholder_username": "用户名",
      "auth.placeholder_username_reg": "3 位以上，字母/数字/下划线",
      "auth.placeholder_password": "密码",
      "auth.placeholder_password_reg": "至少 6 位",
      "auth.placeholder_nickname": "将展示给其他用户",
      "auth.btn_login": "登录",
      "auth.btn_register": "注册",
      "auth.tip": "登录后可进入管理中心发布帖子和交易信息。",
      "auth.login_title": "登录 · 喵友圈",
      "auth.register_title": "注册 · 喵友圈",
      "auth.login_heading": "欢迎回来",
      "auth.register_heading": "创建你的账号",
      "auth.login_lede": "登录继续分享你的宠物日常、管理交易与消息。",
      "auth.register_lede": "几秒完成注册，立即发帖、发布交易、收发私信。",
      "auth.label_username": "用户名",
      "auth.label_password": "密码",
      "auth.label_nickname": "昵称",
      "auth.hint_username": "3 位以上，支持字母、数字、下划线",
      "auth.hint_password": "至少 6 位，建议包含字母和数字",
      "auth.no_account": "还没有账号？",
      "auth.have_account": "已经有账号？",
      "auth.go_login": "返回登录",
      "auth.go_register": "立即注册",
      "auth.error_required": "请填写用户名和密码",
      "auth.error_validation": "用户名至少 3 位，密码至少 6 位",
      "auth.error_login": "登录失败，请检查账号密码",
      "auth.error_register": "注册失败，请稍后再试",
      "auth.error_rate_limit": "尝试过于频繁，请稍后再试",
      "auth.error_agreement": "请先阅读并同意用户协议与隐私政策",
      "auth.label_phone_email": "手机号 / 邮箱",
      "auth.placeholder_account": "请输入您的账号",
      "auth.login_tagline": "登录以继续您的探索之旅",
      "auth.forgot_password": "忘记密码？",
      "auth.other_login_methods": "其他登录方式",
      "auth.legal_login": "登录即代表您同意 MEOW 的",
      "auth.terms_of_service": "服务条款",
      "auth.privacy_policy": "隐私政策",
      "auth.register_tagline": "加入喵圈，发现更多可爱日常",
      "auth.label_phone": "手机号码",
      "auth.label_code": "验证码",
      "auth.send_code": "获取验证码",
      "auth.send_code_wait": "秒后重试",
      "auth.send_code_toast": "短信验证即将上线，当前为演示流程",
      "auth.send_code_ok": "验证码已发送（开发环境可在服务端设置 MEOW_LOG_SMS_CODE=1 查看日志）",
      "auth.error_phone_invalid": "请输入有效的手机号码",
      "auth.error_sms_required": "填写手机号后，请先获取并填写验证码",
      "auth.placeholder_phone": "输入您的手机号",
      "auth.placeholder_code": "输入验证码",
      "auth.placeholder_password_register": "设置登录密码",
      "auth.placeholder_username_register": "给自己起个好听的名字",
      "auth.agreement_html": "我已阅读并同意",
      "auth.user_agreement_link": "《用户协议》",
      "auth.agreement_and": "与",
      "auth.legal_terms_joiner": "和",
      "auth.privacy_policy_link": "《隐私政策》",
      "auth.btn_register_submit": "立即注册",
      "auth.direct_login": "直接登录",
      "auth.social_coming": "第三方登录即将上线",
      "auth.forgot_coming": "找回密码功能即将上线",
      "section.latest_posts": "最新帖子",
      "section.listings": "交易信息",
      "action.refresh": "刷新",
      "post.view_comments": "查看与评论",
      "post.placeholder_comment": "说点什么...",
      "post.btn_comment": "发表评论",
      "dashboard.title": "我的管理中心",
      "dashboard.subtitle": "发布帖子、发布交易、管理我的内容",
      "dashboard.not_login": "请先登录",
      "dashboard.not_login_tip": "管理中心仅登录用户可见。",
      "dashboard.go_home": "返回首页登录",
      "dashboard.nav_compose_post": "发布帖子",
      "dashboard.nav_compose_listing": "发布交易",
      "dashboard.nav_my_posts": "我的帖子",
      "dashboard.nav_my_listings": "我的交易",
      "form.title": "标题",
      "form.content": "写下你的日常分享...",
      "form.category_daily": "日常分享",
      "form.category_help": "求助问答",
      "form.category_activity": "线下活动",
      "form.category_trade": "交易信息",
      "form.tags": "标签，逗号分隔（如：橘猫,饮食）",
      "form.btn_publish_post": "发布帖子",
      "form.listing_title": "商品/服务标题",
      "form.listing_description": "描述信息",
      "form.type_product": "商品",
      "form.type_service": "服务",
      "form.type_adopt": "领养",
      "form.price": "价格（分），例如 9900",
      "form.currency": "币种",
      "form.btn_publish_listing": "发布交易",
      "admin.title": "喵友圈后台管理",
      "admin.subtitle": "仅管理员可访问操作接口（帖子/评论/交易治理）",
      "admin.auth_title": "管理员认证",
      "admin.placeholder_key": "输入 ADMIN_KEY",
      "admin.btn_load": "保存并加载数据",
      "admin.overview": "运营总览",
      "admin.metric_posts": "帖子",
      "admin.metric_comments": "评论",
      "admin.metric_listings": "交易",
      "admin.manage_posts": "帖子管理",
      "admin.manage_comments": "评论管理",
      "admin.manage_listings": "交易管理",
      "admin.btn_delete_post": "删除帖子",
      "admin.btn_delete_comment": "删除评论",
      "admin.btn_delete_listing": "删除交易",
      "doc.title": "喵友圈系统可视化文档",
      "doc.back": "返回业务页面",
      "doc.overview": "系统全景",
      "doc.capabilities": "能力地图",
      "doc.layers": "分层架构说明",
      "doc.api": "API 模块视图",
      "doc.envelope": "统一响应结构",
      "doc.security": "安全策略",
      "doc.mobile": "移动端接入策略",
      "doc.mobile_strategy": "建议策略",
      "doc.android_stack": "Android 推荐技术栈",
      "doc.roadmap": "演进路线图",
      "common.delete": "删除",
      "common.edit": "编辑",
      "common.no_items": "暂无内容",
      "common.unknown": "未知",
      "common.no_description": "暂无描述",
      "common.no_comments": "暂时没有评论",
      "common.empty_posts_hint": "还没有帖子。登录后前往管理中心发布第一篇。",
      "common.empty_listings": "暂无交易信息",
      "common.error_load_posts": "加载帖子失败",
      "common.error_load_listings": "加载交易失败",
      "common.confirm_delete_post": "确认删除这条帖子吗？",
      "common.confirm_delete_listing": "确认删除这条交易吗？",
      "alert.register_success": "注册成功！前往管理中心发布第一条内容～",
      "alert.login_first": "请先登录",
      "alert.login_to_comment": "请先登录再评论",
      "meta.author": "作者",
      "meta.seller": "卖家",
      "meta.price": "价格",
      "meta.published_at": "发布于",
      "user.greeting": "你好，{name}",
      "alert.publish_success": "发布成功！",
      "alert.update_success": "已保存",
      "alert.draft_saved": "草稿已保存在本机",
      "common.empty_my_posts": "你还没有发布帖子",
      "common.empty_my_listings": "你还没有发布交易",
      "meta.last_reply": "最近回复",
      "dashboard.stitch_zone": "Kitty Circle · 管理中心",
      "dashboard.stitch_brand": "喵友圈",
      "dashboard.stitch_subnav": "统一导航 · 管理中心",
      "dashboard.stitch_admin_title": "管理中心",
      "dashboard.stitch_admin_sub": "Management Dashboard",
      "dashboard.create_new": "新建",
      "dashboard.nav_stitch_trades": "我的交易",
      "dashboard.nav_stitch_profile": "个人资料",
      "dashboard.nav_stitch_notif": "通知中心",
      "dashboard.nav_stitch_dm": "私信",
      "dashboard.compose_post_title": "发布新帖",
      "dashboard.compose_post_sub": "与喵友分享日常、求助与活动",
      "dashboard.compose_listing_title": "发布交易",
      "dashboard.compose_listing_sub": "左侧图库，右侧标题、类型、价格与描述（与 Stitch 稿一致）",
      "dashboard.stitch_create_new": "新建",
      "dashboard.editing_badge": "编辑中",
      "dashboard.cancel_edit": "取消编辑",
      "form.save_draft": "存草稿",
      "form.category_label": "分类",
      "form.media_block": "媒体文件",
      "form.drop_hint": "将图片或视频拖到此处，或点击上传",
      "form.drop_formats": "支持 JPG、PNG、MP4 等，按服务器限制",
      "form.tags_label": "标签",
      "form.tag_add_placeholder": "输入标签后按回车",
      "form.visibility": "可见性",
      "form.visibility_public": "公开 · 与 Stitch 设计稿一致，所有登录用户可见",
      "form.shortcut_hint": "草稿保存在本机浏览器，换设备不会同步",
      "form.type_label": "类型",
      "form.listing_drop": "点击或拖入媒体",
      "form.listing_media_hint": "高分辨率 JPEG / PNG，按服务器限制",
      "form.stitch_price_amount": "价格",
      "form.stitch_price_minor_hint": "金额将按所选币种以「分」为单位提交",
      "dashboard.nav_media": "媒体库",
      "dashboard.nav_my_orders": "我的订单",
      "media.upload_image": "上传图片 (≤10MB)",
      "media.upload_video": "上传视频 (≤200MB，mp4/webm/mov)",
      "media.btn_upload": "上传",
      "media.copy_id": "复制 ID",
      "media.stitch_sub": "管理已上传的图片、视频与素材。",
      "media.filter_all": "全部",
      "media.filter_photos": "图片",
      "media.filter_videos": "视频",
      "media.empty": "尚未上传媒体",
      "media.attach_hint": "可关联的媒体 ID (逗号分隔)",
      "media.pick": "选择",
      "media.selected": "已选 {n} 个",
      "order.tab_buyer": "我买的",
      "order.tab_seller": "我卖的",
      "order.btn_pay": "支付",
      "order.btn_cancel": "取消",
      "order.btn_ship": "发货",
      "order.btn_complete": "确认收货",
      "order.btn_refund": "退款",
      "order.col_listing": "商品 / 说明",
      "order.col_amount": "金额",
      "order.col_status": "状态",
      "order.col_people": "买家 / 卖家",
      "order.col_actions": "操作",
      "order.empty": "暂无订单",
      "order.status.pending_payment": "待支付",
      "order.status.paid": "已支付",
      "order.status.shipped": "已发货",
      "order.status.completed": "已完成",
      "order.status.cancelled": "已取消",
      "order.status.refunded": "已退款",
      "order.stitch_title": "订单管理",
      "order.stitch_sub": "与 Stitch 一致：统计、筛选、表格与导出",
      "order.export_csv": "导出 CSV",
      "order.filter_all": "全部",
      "order.filter_pending": "待支付",
      "order.filter_processing": "处理中",
      "order.filter_completed": "已完成",
      "order.col_id": "订单号",
      "order.col_date": "日期",
      "order.col_total": "金额",
      "order.stitch_col_customer": "对方 / 交易",
      "order.stat_revenue": "总成交额",
      "order.stat_revenue_hint": "当前角色下可统计的订单金额",
      "order.stat_active": "进行中",
      "order.stat_avg": "均单价",
      "order.stat_avg_hint": "按当前列表计算",
      "order.stat_urgent_msg": "需关注：{n} 笔",
      "order.stat_action": "需关注",
      "order.counterparty_id": "用户 {id}",
      "order.stitch_table_hint": "与 Stitch 表头、操作列布局一致",
      "order.stitch_sub2": "跟踪、处理并管理你最近的销售订单。",
      "order.stat_revenue_bento": "总成交额",
      "order.stat_active_bento": "进行中",
      "order.stat_satisfaction_bento": "客户满意度",
      "order.stat_trend_na": "暂无同期对比",
      "order.stat_satisfaction_sub": "评价与星级将接入后显示",
      "order.filter_all_orders": "全部订单",
      "order.filter_options": "筛选",
      "order.col_customer": "客户",
      "order.footer_range": "第 1 – {m} 条，本角色下共 {n} 笔",
      "order.listing_fallback": "（无标题）",
      "order.empty_csv": "没有可导出的行",
      "form.btn_publish": "发布",
      "form.btn_publish_trade": "发布交易",
      "form.stitch_title_ph": "在此输入标题…",
      "form.stitch_content_ph": "在此撰写正文…",
      "form.drop_hint_line1": "将图片或视频拖到此处",
      "form.browse_files": "浏览文件",
      "form.stitch_cat_daily": "日常",
      "form.stitch_cat_tips": "养宠技巧",
      "form.stitch_cat_questions": "求助问答",
      "form.stitch_cat_trade": "交易信息",
      "form.stitch_yuan_hint": "将同步为分（cents）提交",
      "form.stitch_price_yuan": "价格（元）",
      "form.format_title_bold": "粗体",
      "form.format_title_italic": "斜体",
      "form.format_title_underline": "下划线",
      "form.format_title_ul": "无序列表",
      "form.format_title_ol": "有序列表",
      "form.format_title_align_outdent": "减少缩进",
      "form.format_title_indent": "增加缩进",
      "form.format_title_link": "插入链接",
      "form.link_url_prompt": "链接地址",
      "form.visibility_public_label": "公开",
      "form.visibility_public_desc": "登录用户均可见",
      "dashboard.stitch_create_post": "发布新帖",
      "dashboard.stitch_listing_title": "发布交易 / 商品",
      "dashboard.header_brand": "Kitty Circle Admin",
      "dashboard.search_placeholder": "搜索帖子、交易…",
      "dashboard.search_placeholder_orders": "搜索订单号、商品…",
      "dashboard.search_placeholder_posts": "搜索标题或正文…",
      "dashboard.search_placeholder_listings": "搜索交易标题…",
      "dashboard.search_placeholder_messages": "搜索联系人、消息…",
      "dashboard.stitch_my_posts_title": "我的帖子",
      "dashboard.stitch_my_posts_sub": "已发布与本地草稿",
      "dashboard.stitch_my_posts_sub2": "管理与浏览你已发布的内容。",
      "dashboard.posts_tab_all": "全部帖子",
      "dashboard.posts_filter_published": "已发布",
      "dashboard.posts_filter_drafts": "草稿",
      "dashboard.posts_stat_published": "已发布 {n} 篇",
      "dashboard.posts_stat_drafts": "本地草稿 {n} 份",
      "dashboard.posts_stat_total_label": "帖子总数",
      "dashboard.posts_stat_views_label": "总浏览",
      "dashboard.posts_views_na": "—",
      "dashboard.posts_load_more": "加载更多",
      "dashboard.posts_all_loaded": "已全部加载",
      "dashboard.published_badge": "已发布",
      "dashboard.draft_untitled": "未命名草稿",
      "dashboard.draft_badge": "草稿",
      "dashboard.draft_continue": "继续编辑",
      "notify.stitch_title": "通知中心",
      "notify.stitch_sub": "按分类查看",
      "notify.cat_all": "全部",
      "notify.categories_label": "分类",
      "notify.categories_label": "分类",
      "profile.stitch_title": "资料与偏好",
      "profile.stitch_sub": "Bento 布局，偏好保存在本机",
      "profile.pref_block": "偏好",
      "profile.pref_compact": "列表紧凑",
      "profile.pref_notify": "系统通知",
      "profile.btn_cancel": "放弃更改",
      "common.confirm_delete_draft": "确定清除本地草稿？",
      "listing.btn_buy": "立即购买",
      "report.btn": "举报",
      "report.placeholder": "请输入举报原因",
      "report.submitted": "已提交举报，感谢协助社区治理",
      "admin.nav_media": "媒体审核",
      "admin.nav_reports": "举报处理",
      "admin.nav_orders": "订单总览",
      "admin.btn_approve": "通过",
      "admin.btn_reject": "拒绝",
      "admin.btn_resolve": "处理并删除",
      "admin.btn_dismiss": "驳回",
      "nav.search_placeholder": "搜索帖子、交易...",
      "nav.compose": "发帖",
      "nav.notifications": "通知",
      "nav.settings": "设置",
      "nav.messages": "私信",
      "stitch.tagline": "社区探索",
      "stitch.nav_home": "首页",
      "stitch.nav_discover": "发现",
      "stitch.nav_market": "市集",
      "stitch.nav_messages": "消息",
      "stitch.nav_me": "我的",
      "stitch.search_posts": "搜索猫咪日常、好物推荐...",
      "stitch.loading_more": "加载更多喵星人...",
      "stitch.hot_topics": "热门话题",
      "stitch.rec_circles": "推荐圈子",
      "stitch.view_all": "查看全部",
      "stitch.join": "加入",
      "stitch.filter_follow_tip": "关注动态会显示你已关注用户的帖子；请先登录。",
      "stitch.filter_follow_login": "查看「关注」请先登录",
      "stitch.like_login": "登录后即可点赞",
      "stitch.follow": "关注",
      "stitch.following": "已关注",
      "stitch.follow_login": "登录后即可关注作者",
      "stitch.followed_ok": "已关注",
      "stitch.unfollowed_ok": "已取消关注",
      "stitch.filter_rec": "推荐",
      "stitch.filter_new": "最新",
      "stitch.filter_follow": "关注",
      "stitch.post_detail": "帖子详情",
      "stitch.poster": "发布者",
      "stitch.market_title": "市集",
      "stitch.market_heading": "好物市集",
      "stitch.market_lede": "领养、用品、服务——逛一逛同好发布的交易信息。",
      "stitch.price_negotiate": "面议 / 详见描述",
      "stitch.compose_title": "发布新帖",
      "stitch.compose_heading": "发布新帖",
      "stitch.compose_title_hint": "填写标题会有更多赞哦~",
      "stitch.compose_category": "分类",
      "stitch.discover_title": "发现圈子",
      "stitch.discover_page_title": "咪友圈",
      "stitch.discover_search_ph": "搜索你感兴趣的圈子...",
      "stitch.discover_tip": "以下为示例圈子卡片；后续可接入真实圈子数据与帖子聚合。",
      "stitch.chip_all": "全部圈子",
      "stitch.chip_newbie": "新手养猫",
      "stitch.chip_breed": "品种讨论",
      "stitch.chip_gear": "好物分享",
      "stitch.chip_health": "医疗健康",
      "stitch.circle_orange": "橘猫大联盟",
      "stitch.circle_orange_desc": "十个橘猫九个胖，还有一个压倒炕。",
      "stitch.circle_newbie": "新手铲屎官互助",
      "stitch.circle_newbie_desc": "保姆级教程与热心答疑。",
      "stitch.circle_black": "黑猫玄学社",
      "stitch.circle_black_desc": "神秘优雅的小精灵。",
      "stitch.circle_market": "好物种草机",
      "stitch.circle_market_desc": "跳转真实交易市集。",
      "stitch.messages_title": "消息中心",
      "stitch.messages_tip": "完整私信与通知请在管理中心使用。",
      "stitch.messages_cta": "打开管理中心",
      "stitch.profile_edit": "编辑资料",
      "stitch.profile_share": "分享主页",
      "stitch.profile_share_ok": "链接已复制",
      "stitch.profile_title": "我的",
      "stitch.back_home": "返回首页",
      "hero.title": "把对毛孩子的爱，分享给同好。",
      "hero.subtitle": "发布日常、交换经验、可信交易——一站式宠物主人社区，像翻开一本讲究的杂志。",
      "hero.btn_primary": "开始分享",
      "hero.btn_secondary": "浏览交易",
      "hero.eyebrow": "社区 · 正在刊载",
      "hero.index_primary_caption": "篇帖子正在被阅读与评论",
      "home.eyebrow_posts": "时间线 · 社区",
      "home.eyebrow_listings": "市集 · 可交易",
      "stat.posts": "帖子",
      "stat.listings": "交易",
      "stat.users": "用户",
      "dashboard.nav_profile": "个人资料",
      "dashboard.nav_notifications": "通知中心",
      "dashboard.nav_messages": "私信",
      "profile.title": "资料设置",
      "profile.nickname": "昵称",
      "profile.avatar_url": "头像 URL（可上传媒体后复制其 URL）",
      "profile.bio": "个人简介",
      "profile.btn_save": "保存资料",
      "profile.saved": "资料已更新",
      "notify.empty": "暂无通知",
      "notify.mark_all_read": "全部标为已读",
      "notify.badge_new": "新",
      "notify.kind_comment": "新评论",
      "notify.kind_order": "订单状态",
      "notify.kind_report_handled": "举报处理",
      "notify.kind_message": "新私信",
      "notify.kind_system": "系统",
      "message.empty": "还没有私信",
      "message.placeholder": "输入消息...",
      "message.btn_send": "发送",
      "message.start_new": "给该用户发私信",
      "message.target_user_id": "对方用户 ID",
      "message.filter_all": "全部会话",
      "message.filter_unread": "未读",
      "message.filter_trades": "交易",
      "search.title": "搜索结果",
      "search.placeholder": "关键字",
      "search.btn": "搜索",
      "search.no_result": "没有找到匹配内容",
      "search.tab_all": "全部",
      "search.tab_posts": "帖子",
      "search.tab_listings": "交易",
      "admin.nav_audit": "审计日志",
      "admin.audit_empty": "暂无审计记录",
      "admin.metric_users": "用户",
      "admin.metric_orders": "订单",
      "admin.metric_media": "媒体",
      "admin.metric_reports": "举报",
      "payment.method": "支付方式",
    },
    en: {
      "app.title": "Meow Circle",
      "app.subtitle": "A community for cat & pet owners to share and trade",
      "nav.docs": "Docs",
      "nav.dashboard": "My Console",
      "nav.home": "Back to Site",
      "nav.login": "Sign in",
      "nav.register": "Sign up",
      "nav.logout": "Logout",
      "nav.settings_theme": "Theme",
      "nav.settings_lang": "Language",
      "auth.title": "Sign in / Sign up",
      "auth.tab_login": "Sign in",
      "auth.tab_register": "Sign up",
      "auth.placeholder_username": "Your username",
      "auth.placeholder_username_reg": "3+ chars · letters, digits, _",
      "auth.placeholder_password": "Your password",
      "auth.placeholder_password_reg": "At least 6 characters",
      "auth.placeholder_nickname": "Shown to other members",
      "auth.btn_login": "Sign in",
      "auth.btn_register": "Sign up",
      "auth.tip": "After signing in, head to the console to publish posts and listings.",
      "auth.login_title": "Sign in · Meow Circle",
      "auth.register_title": "Sign up · Meow Circle",
      "auth.login_heading": "Welcome back",
      "auth.register_heading": "Create your account",
      "auth.login_lede": "Sign in to keep sharing daily stories, manage listings and messages.",
      "auth.register_lede": "Takes seconds. Start posting, trading and messaging right away.",
      "auth.label_username": "Username",
      "auth.label_password": "Password",
      "auth.label_nickname": "Nickname",
      "auth.hint_username": "3+ characters · letters, digits, underscore",
      "auth.hint_password": "At least 6 characters; mix letters and digits",
      "auth.no_account": "No account yet?",
      "auth.have_account": "Already have an account?",
      "auth.go_login": "Back to sign in",
      "auth.go_register": "Create one now",
      "auth.error_required": "Please enter both username and password",
      "auth.error_validation": "Username ≥3 chars, password ≥6 chars",
      "auth.error_login": "Sign-in failed, please check your credentials",
      "auth.error_register": "Sign-up failed, please try again",
      "auth.error_rate_limit": "Too many attempts, please wait",
      "auth.error_agreement": "Please accept the Terms and Privacy Policy",
      "auth.label_phone_email": "Phone / Email",
      "auth.placeholder_account": "Enter your account",
      "auth.login_tagline": "Sign in to continue exploring",
      "auth.forgot_password": "Forgot password?",
      "auth.other_login_methods": "Other sign-in methods",
      "auth.legal_login": "By signing in you agree to MEOW’s",
      "auth.terms_of_service": "Terms of Service",
      "auth.privacy_policy": "Privacy Policy",
      "auth.register_tagline": "Join the circle — more cute daily moments",
      "auth.label_phone": "Mobile number",
      "auth.label_code": "Verification code",
      "auth.send_code": "Get code",
      "auth.send_code_wait": "s to retry",
      "auth.send_code_toast": "SMS verification coming soon — demo only",
      "auth.send_code_ok": "Code sent (dev: set MEOW_LOG_SMS_CODE=1 on server to log it)",
      "auth.error_phone_invalid": "Please enter a valid phone number",
      "auth.error_sms_required": "With a phone number, get the code and enter it",
      "auth.placeholder_phone": "Your phone number",
      "auth.placeholder_code": "Enter the code",
      "auth.placeholder_password_register": "Choose a password",
      "auth.placeholder_username_register": "Pick a username you like",
      "auth.agreement_html": "I have read and agree to the",
      "auth.user_agreement_link": "User Agreement",
      "auth.agreement_and": "and",
      "auth.legal_terms_joiner": " and ",
      "auth.privacy_policy_link": "Privacy Policy",
      "auth.btn_register_submit": "Sign up now",
      "auth.direct_login": "Sign in",
      "auth.social_coming": "Social sign-in coming soon",
      "auth.forgot_coming": "Password recovery coming soon",
      "section.latest_posts": "Latest Posts",
      "section.listings": "Listings",
      "action.refresh": "Refresh",
      "post.view_comments": "View & Comment",
      "post.placeholder_comment": "Say something...",
      "post.btn_comment": "Post Comment",
      "dashboard.title": "My Console",
      "dashboard.subtitle": "Publish posts and listings, manage my content",
      "dashboard.not_login": "Please sign in first",
      "dashboard.not_login_tip": "Console is only visible to signed-in users.",
      "dashboard.go_home": "Back to home to sign in",
      "dashboard.nav_compose_post": "New Post",
      "dashboard.nav_compose_listing": "New Listing",
      "dashboard.nav_my_posts": "My Posts",
      "dashboard.nav_my_listings": "My Listings",
      "form.title": "Title",
      "form.content": "Share your daily life...",
      "form.category_daily": "Daily Share",
      "form.category_help": "Q & A",
      "form.category_activity": "Activity",
      "form.category_trade": "Trade Info",
      "form.tags": "Tags, comma separated (e.g. cat,food)",
      "form.btn_publish_post": "Publish Post",
      "form.listing_title": "Product / Service Title",
      "form.listing_description": "Description",
      "form.type_product": "Product",
      "form.type_service": "Service",
      "form.type_adopt": "Adoption",
      "form.price": "Price in cents (e.g. 9900)",
      "form.currency": "Currency",
      "form.btn_publish_listing": "Publish Listing",
      "admin.title": "Meow Circle Admin",
      "admin.subtitle": "Only admins can access management APIs.",
      "admin.auth_title": "Admin Authentication",
      "admin.placeholder_key": "Enter ADMIN_KEY",
      "admin.btn_load": "Save & Load",
      "admin.overview": "Overview",
      "admin.metric_posts": "Posts",
      "admin.metric_comments": "Comments",
      "admin.metric_listings": "Listings",
      "admin.manage_posts": "Post Management",
      "admin.manage_comments": "Comment Management",
      "admin.manage_listings": "Listing Management",
      "admin.btn_delete_post": "Delete Post",
      "admin.btn_delete_comment": "Delete Comment",
      "admin.btn_delete_listing": "Delete Listing",
      "doc.title": "System Architecture Doc",
      "doc.back": "Back",
      "doc.overview": "System Overview",
      "doc.capabilities": "Capability Map",
      "doc.layers": "Layered Architecture",
      "doc.api": "API Modules",
      "doc.envelope": "Response Envelope",
      "doc.security": "Security",
      "doc.mobile": "Mobile Integration",
      "doc.mobile_strategy": "Strategy",
      "doc.android_stack": "Android Stack",
      "doc.roadmap": "Roadmap",
      "common.delete": "Delete",
      "common.edit": "Edit",
      "common.no_items": "No items",
      "common.unknown": "unknown",
      "common.no_description": "No description",
      "common.no_comments": "No comments yet",
      "common.empty_posts_hint": "No posts yet. Sign in and head to the console to publish the first one.",
      "common.empty_listings": "No listings yet",
      "common.error_load_posts": "Failed to load posts",
      "common.error_load_listings": "Failed to load listings",
      "common.confirm_delete_post": "Delete this post?",
      "common.confirm_delete_listing": "Delete this listing?",
      "alert.register_success": "Signed up! Head to the console to publish your first content.",
      "alert.login_first": "Please sign in first",
      "alert.login_to_comment": "Please sign in to comment",
      "meta.author": "Author",
      "meta.seller": "Seller",
      "meta.price": "Price",
      "meta.published_at": "Posted at",
      "user.greeting": "Hi, {name}",
      "alert.publish_success": "Published!",
      "alert.update_success": "Saved",
      "alert.draft_saved": "Draft saved locally",
      "common.empty_my_posts": "You have not published any posts",
      "common.empty_my_listings": "You have not published any listings",
      "meta.last_reply": "Last reply",
      "dashboard.stitch_zone": "Kitty Circle · Admin",
      "dashboard.stitch_brand": "Kitty Circle",
      "dashboard.stitch_subnav": "Unified nav · Console",
      "dashboard.stitch_admin_title": "Admin Center",
      "dashboard.stitch_admin_sub": "Management Dashboard",
      "dashboard.create_new": "Create New",
      "dashboard.nav_stitch_trades": "My Trades",
      "dashboard.nav_stitch_profile": "Profile",
      "dashboard.nav_stitch_notif": "Notifications",
      "dashboard.nav_stitch_dm": "Direct Messages",
      "dashboard.compose_post_title": "New post",
      "dashboard.compose_post_sub": "Share daily life, help, and events",
      "dashboard.compose_listing_title": "New listing",
      "dashboard.compose_listing_sub": "Media on the left; title, type, price, and description on the right (Stitch layout).",
      "dashboard.stitch_create_new": "Create New",
      "dashboard.editing_badge": "Editing",
      "dashboard.cancel_edit": "Cancel edit",
      "form.save_draft": "Save draft",
      "form.category_label": "Category",
      "form.media_block": "Media",
      "form.drop_hint": "Drop images or video here, or click to upload",
      "form.drop_formats": "JPG, PNG, MP4, etc. (server limits apply)",
      "form.tags_label": "Tags",
      "form.tag_add_placeholder": "Type a tag and press Enter",
      "form.visibility": "Visibility",
      "form.visibility_public": "Public · all signed-in users (same as Stitch)",
      "form.shortcut_hint": "Drafts are stored in this browser only",
      "form.type_label": "Type",
      "form.listing_drop": "Click or drop media",
      "form.listing_media_hint": "High-res JPEG or PNG (server limits apply)",
      "form.stitch_price_amount": "Price",
      "form.stitch_price_minor_hint": "Amount is submitted in minor units (cents) for the selected currency.",
      "dashboard.nav_media": "Media Library",
      "dashboard.nav_my_orders": "My Orders",
      "media.upload_image": "Upload image (≤10MB)",
      "media.upload_video": "Upload video (≤200MB, mp4/webm/mov)",
      "media.btn_upload": "Upload",
      "media.copy_id": "Copy ID",
      "media.stitch_sub": "Manage photos, videos, and graphics you uploaded.",
      "media.filter_all": "All",
      "media.filter_photos": "Photos",
      "media.filter_videos": "Videos",
      "media.empty": "No media uploaded",
      "media.attach_hint": "Attach media IDs (comma separated)",
      "media.pick": "Pick",
      "media.selected": "{n} selected",
      "order.tab_buyer": "As buyer",
      "order.tab_seller": "As seller",
      "order.btn_pay": "Pay",
      "order.btn_cancel": "Cancel",
      "order.btn_ship": "Ship",
      "order.btn_complete": "Confirm",
      "order.btn_refund": "Refund",
      "order.col_listing": "Listing",
      "order.col_amount": "Amount",
      "order.col_status": "Status",
      "order.col_people": "Buyer / seller",
      "order.col_actions": "Actions",
      "order.empty": "No orders",
      "order.status.pending_payment": "Pending payment",
      "order.status.paid": "Paid",
      "order.status.shipped": "Shipped",
      "order.status.completed": "Completed",
      "order.status.cancelled": "Cancelled",
      "order.status.refunded": "Refunded",
      "order.stitch_title": "Order management",
      "order.stitch_sub": "Stitch layout: stats, filters, table, export",
      "order.export_csv": "Export CSV",
      "order.filter_all": "All",
      "order.filter_pending": "Pending",
      "order.filter_processing": "Processing",
      "order.filter_completed": "Completed",
      "order.col_id": "Order ID",
      "order.col_date": "Date",
      "order.col_total": "Total",
      "order.stitch_col_customer": "Counterparty / listing",
      "order.stat_revenue": "Total volume",
      "order.stat_revenue_hint": "Order amounts for the current role",
      "order.stat_active": "Active",
      "order.stat_avg": "Avg. order",
      "order.stat_avg_hint": "From current list",
      "order.stat_urgent_msg": "Needs action: {n}",
      "order.stat_action": "Action needed",
      "order.counterparty_id": "User {id}",
      "order.stitch_table_hint": "Columns align with the Stitch spec",
      "order.stitch_sub2": "Track, fulfill, and manage your recent sales.",
      "order.stat_revenue_bento": "Total revenue",
      "order.stat_active_bento": "Active orders",
      "order.stat_satisfaction_bento": "Customer satisfaction",
      "order.stat_trend_na": "No period comparison yet",
      "order.stat_satisfaction_sub": "Ratings and reviews are not available yet",
      "order.filter_all_orders": "All orders",
      "order.filter_options": "Filter options",
      "order.col_customer": "Customer",
      "order.footer_range": "1 – {m} of {n} in this role",
      "order.listing_fallback": "(No listing title)",
      "order.empty_csv": "No rows to export",
      "form.btn_publish": "Publish",
      "form.btn_publish_trade": "Publish trade",
      "form.stitch_title_ph": "Enter a title…",
      "form.stitch_content_ph": "Write your post…",
      "form.drop_hint_line1": "Drag images or video here",
      "form.browse_files": "Browse files",
      "form.stitch_cat_daily": "Daily",
      "form.stitch_cat_tips": "Pet tips",
      "form.stitch_cat_questions": "Q & A",
      "form.stitch_cat_trade": "Trade",
      "form.stitch_yuan_hint": "Saved as price in cents",
      "form.stitch_price_yuan": "Price (yuan)",
      "form.format_title_bold": "Bold",
      "form.format_title_italic": "Italic",
      "form.format_title_underline": "Underline",
      "form.format_title_ul": "Bullet list",
      "form.format_title_ol": "Numbered list",
      "form.format_title_align_outdent": "Outdent",
      "form.format_title_indent": "Indent",
      "form.format_title_link": "Link",
      "form.link_url_prompt": "Link URL",
      "form.visibility_public_label": "Public",
      "form.visibility_public_desc": "Visible to all signed-in users",
      "dashboard.stitch_create_post": "Create new post",
      "dashboard.stitch_listing_title": "Create listing / trade",
      "dashboard.header_brand": "Kitty Circle Admin",
      "dashboard.search_placeholder": "Search posts, trades…",
      "dashboard.search_placeholder_orders": "Search orders, listings…",
      "dashboard.search_placeholder_posts": "Search title or body…",
      "dashboard.search_placeholder_listings": "Search listing titles…",
      "dashboard.search_placeholder_messages": "Search people or last message…",
      "dashboard.stitch_my_posts_title": "My posts",
      "dashboard.stitch_my_posts_sub": "Published and local drafts",
      "dashboard.stitch_my_posts_sub2": "Manage and review your published content.",
      "dashboard.posts_tab_all": "All posts",
      "dashboard.posts_filter_published": "Published",
      "dashboard.posts_filter_drafts": "Drafts",
      "dashboard.posts_stat_published": "Published: {n}",
      "dashboard.posts_stat_drafts": "Local drafts: {n}",
      "dashboard.posts_stat_total_label": "Total posts",
      "dashboard.posts_stat_views_label": "Total views",
      "dashboard.posts_views_na": "—",
      "dashboard.posts_load_more": "Load more posts",
      "dashboard.posts_all_loaded": "Everything is loaded",
      "dashboard.published_badge": "Published",
      "dashboard.draft_untitled": "Untitled draft",
      "dashboard.draft_badge": "Draft",
      "dashboard.draft_continue": "Continue",
      "notify.stitch_title": "Notifications",
      "notify.stitch_sub": "Filter by kind",
      "notify.cat_all": "All",
      "notify.categories_label": "Categories",
      "profile.stitch_title": "Profile & preferences",
      "profile.stitch_sub": "Bento layout, prefs in local storage",
      "profile.pref_block": "Preferences",
      "profile.pref_compact": "Compact lists",
      "profile.pref_notify": "System notifications",
      "profile.btn_cancel": "Cancel changes",
      "common.confirm_delete_draft": "Clear the local draft?",
      "listing.btn_buy": "Buy now",
      "report.btn": "Report",
      "report.placeholder": "Reason for reporting",
      "report.submitted": "Report submitted, thanks for keeping the community healthy",
      "admin.nav_media": "Media Review",
      "admin.nav_reports": "Reports",
      "admin.nav_orders": "Orders",
      "admin.btn_approve": "Approve",
      "admin.btn_reject": "Reject",
      "admin.btn_resolve": "Resolve & delete",
      "admin.btn_dismiss": "Dismiss",
      "nav.search_placeholder": "Search posts, listings...",
      "nav.compose": "New post",
      "nav.notifications": "Notifications",
      "nav.settings": "Settings",
      "nav.messages": "Messages",
      "stitch.tagline": "Explore",
      "stitch.nav_home": "Home",
      "stitch.nav_discover": "Discover",
      "stitch.nav_market": "Market",
      "stitch.nav_messages": "Messages",
      "stitch.nav_me": "Me",
      "stitch.search_posts": "Search cat life, picks...",
      "stitch.loading_more": "Loading more...",
      "stitch.hot_topics": "Hot topics",
      "stitch.rec_circles": "Circles",
      "stitch.view_all": "See all",
      "stitch.join": "Join",
      "stitch.filter_follow_tip": "The Following tab shows posts from people you follow; please sign in.",
      "stitch.filter_follow_login": "Sign in to use the Following feed",
      "stitch.like_login": "Sign in to like posts",
      "stitch.follow": "Follow",
      "stitch.following": "Following",
      "stitch.follow_login": "Sign in to follow",
      "stitch.followed_ok": "Following this author",
      "stitch.unfollowed_ok": "Unfollowed",
      "stitch.filter_rec": "For you",
      "stitch.filter_new": "Latest",
      "stitch.filter_follow": "Following",
      "stitch.post_detail": "Post",
      "stitch.poster": "Author",
      "stitch.market_title": "Market",
      "stitch.market_heading": "Marketplace",
      "stitch.market_lede": "Adoptions, gear, services from the community.",
      "stitch.price_negotiate": "See description",
      "stitch.compose_title": "New post",
      "stitch.compose_heading": "New post",
      "stitch.compose_title_hint": "Add a title",
      "stitch.compose_category": "Category",
      "stitch.discover_title": "Discover",
      "stitch.discover_page_title": "Circles",
      "stitch.discover_search_ph": "Search circles...",
      "stitch.discover_tip": "Sample circles; real data can be wired later.",
      "stitch.chip_all": "All",
      "stitch.chip_newbie": "New owners",
      "stitch.chip_breed": "Breeds",
      "stitch.chip_gear": "Gear",
      "stitch.chip_health": "Health",
      "stitch.circle_orange": "Orange cat union",
      "stitch.circle_orange_desc": "Chonky orange cats welcome.",
      "stitch.circle_newbie": "New owner help",
      "stitch.circle_newbie_desc": "Tutorials and Q&A.",
      "stitch.circle_black": "Black cat club",
      "stitch.circle_black_desc": "Elegant void cats.",
      "stitch.circle_market": "Gear picks",
      "stitch.circle_market_desc": "Go to the real marketplace.",
      "stitch.messages_title": "Messages",
      "stitch.messages_tip": "Use the console for full DMs and notifications.",
      "stitch.messages_cta": "Open console",
      "stitch.profile_edit": "Edit profile",
      "stitch.profile_share": "Share",
      "stitch.profile_share_ok": "Link copied",
      "stitch.profile_title": "Profile",
      "stitch.back_home": "Back to home",
      "hero.title": "Share the love for your furry family.",
      "hero.subtitle": "Daily stories, trusted marketplace, one community for pet owners — read like a magazine, not another dashboard.",
      "hero.btn_primary": "Start sharing",
      "hero.btn_secondary": "Browse listings",
      "hero.eyebrow": "Community · Now live",
      "hero.index_primary_caption": "posts being read and discussed",
      "home.eyebrow_posts": "Timeline · Community",
      "home.eyebrow_listings": "Market · Available",
      "stat.posts": "Posts",
      "stat.listings": "Listings",
      "stat.users": "Members",
      "dashboard.nav_profile": "Profile",
      "dashboard.nav_notifications": "Inbox",
      "dashboard.nav_messages": "Messages",
      "profile.title": "Profile",
      "profile.nickname": "Nickname",
      "profile.avatar_url": "Avatar URL (upload to media then copy the URL)",
      "profile.bio": "About me",
      "profile.btn_save": "Save profile",
      "profile.saved": "Profile updated",
      "notify.empty": "No notifications",
      "notify.mark_all_read": "Mark all read",
      "notify.badge_new": "New",
      "notify.kind_comment": "Comment",
      "notify.kind_order": "Order",
      "notify.kind_report_handled": "Report",
      "notify.kind_message": "Message",
      "notify.kind_system": "System",
      "message.empty": "No messages",
      "message.placeholder": "Type a message...",
      "message.btn_send": "Send",
      "message.start_new": "Send a message to a user",
      "message.target_user_id": "Recipient user ID",
      "message.filter_all": "All Chats",
      "message.filter_unread": "Unread",
      "message.filter_trades": "Trades",
      "search.title": "Search results",
      "search.placeholder": "keyword",
      "search.btn": "Search",
      "search.no_result": "No matches",
      "search.tab_all": "All",
      "search.tab_posts": "Posts",
      "search.tab_listings": "Listings",
      "admin.nav_audit": "Audit Log",
      "admin.audit_empty": "No audit records",
      "admin.metric_users": "Users",
      "admin.metric_orders": "Orders",
      "admin.metric_media": "Media",
      "admin.metric_reports": "Reports",
      "payment.method": "Payment method",
    },
    ja: {
      "app.title": "ニャンコサークル",
      "app.subtitle": "猫とペットの飼い主のための共有・取引コミュニティ",
      "nav.docs": "ドキュメント",
      "nav.dashboard": "マイコンソール",
      "nav.home": "サイトへ戻る",
      "nav.login": "ログイン",
      "nav.register": "登録",
      "nav.logout": "ログアウト",
      "nav.settings_theme": "テーマ",
      "nav.settings_lang": "言語",
      "auth.title": "ログイン / 登録",
      "auth.tab_login": "ログイン",
      "auth.tab_register": "登録",
      "auth.placeholder_username": "ユーザー名",
      "auth.placeholder_username_reg": "3文字以上、英数字/アンダースコア",
      "auth.placeholder_password": "パスワード",
      "auth.placeholder_password_reg": "6文字以上",
      "auth.placeholder_nickname": "他のメンバーに表示されます",
      "auth.btn_login": "ログイン",
      "auth.btn_register": "登録",
      "auth.tip": "ログイン後、コンソールで投稿と取引を公開できます。",
      "auth.login_title": "ログイン · ニャンコサークル",
      "auth.register_title": "登録 · ニャンコサークル",
      "auth.login_heading": "おかえりなさい",
      "auth.register_heading": "アカウント作成",
      "auth.login_lede": "ログインして日々のシェア、取引、メッセージを続けましょう。",
      "auth.register_lede": "数秒で登録完了。投稿・取引・メッセージがすぐに始められます。",
      "auth.label_username": "ユーザー名",
      "auth.label_password": "パスワード",
      "auth.label_nickname": "ニックネーム",
      "auth.hint_username": "3文字以上、英数字とアンダースコア",
      "auth.hint_password": "6文字以上、英字と数字を含めると安全",
      "auth.no_account": "アカウントをお持ちでないですか？",
      "auth.have_account": "すでにアカウントをお持ちですか？",
      "auth.go_login": "ログインへ戻る",
      "auth.go_register": "今すぐ登録",
      "auth.error_required": "ユーザー名とパスワードを入力してください",
      "auth.error_validation": "ユーザー名は3文字以上、パスワードは6文字以上",
      "auth.error_login": "ログインできませんでした。資格情報を確認してください",
      "auth.error_register": "登録に失敗しました。しばらくしてからお試しください",
      "auth.error_rate_limit": "試行が多すぎます。しばらくお待ちください",
      "auth.error_agreement": "利用規約とプライバシーポリシーに同意してください",
      "auth.label_phone_email": "電話 / メール",
      "auth.placeholder_account": "アカウントを入力",
      "auth.login_tagline": "サインインして探索を続けましょう",
      "auth.forgot_password": "パスワードをお忘れですか？",
      "auth.other_login_methods": "その他のログイン方法",
      "auth.legal_login": "ログインにより MEOW の",
      "auth.terms_of_service": "利用規約",
      "auth.privacy_policy": "プライバシーポリシー",
      "auth.register_tagline": "ニャンコサークルへ — かわいい日常をもっと",
      "auth.label_phone": "電話番号",
      "auth.label_code": "認証コード",
      "auth.send_code": "コード取得",
      "auth.send_code_wait": "秒後に再試行",
      "auth.send_code_toast": "SMS 認証は近日対応（デモ）",
      "auth.send_code_ok": "コードを送信しました（開発: MEOW_LOG_SMS_CODE=1 でログ）",
      "auth.error_phone_invalid": "有効な電話番号を入力してください",
      "auth.error_sms_required": "電話番号を入力した場合は認証コードが必要です",
      "auth.placeholder_phone": "電話番号",
      "auth.placeholder_code": "認証コード",
      "auth.placeholder_password_register": "ログインパスワード",
      "auth.placeholder_username_register": "お好きなユーザー名",
      "auth.agreement_html": "次に同意します",
      "auth.user_agreement_link": "利用規約",
      "auth.agreement_and": "および",
      "auth.legal_terms_joiner": " と ",
      "auth.privacy_policy_link": "プライバシーポリシー",
      "auth.btn_register_submit": "今すぐ登録",
      "auth.direct_login": "ログインへ",
      "auth.social_coming": "ソーシャルログインは近日対応",
      "auth.forgot_coming": "パスワード再設定は近日対応",
      "section.latest_posts": "最新の投稿",
      "section.listings": "取引情報",
      "action.refresh": "更新",
      "post.view_comments": "コメントを見る",
      "post.placeholder_comment": "一言どうぞ...",
      "post.btn_comment": "コメント",
      "dashboard.title": "マイコンソール",
      "dashboard.subtitle": "投稿・取引の公開とコンテンツ管理",
      "dashboard.not_login": "ログインしてください",
      "dashboard.not_login_tip": "コンソールはログイン済みユーザー限定です。",
      "dashboard.go_home": "トップに戻ってログイン",
      "dashboard.nav_compose_post": "投稿を書く",
      "dashboard.nav_compose_listing": "取引を出す",
      "dashboard.nav_my_posts": "自分の投稿",
      "dashboard.nav_my_listings": "自分の取引",
      "form.title": "タイトル",
      "form.content": "日常をシェアしましょう...",
      "form.category_daily": "日常",
      "form.category_help": "相談",
      "form.category_activity": "イベント",
      "form.category_trade": "取引情報",
      "form.tags": "タグ、カンマ区切り",
      "form.btn_publish_post": "投稿する",
      "form.listing_title": "商品 / サービス名",
      "form.listing_description": "説明",
      "form.type_product": "商品",
      "form.type_service": "サービス",
      "form.type_adopt": "里親",
      "form.price": "価格（単位: 分, 例: 9900）",
      "form.currency": "通貨",
      "form.btn_publish_listing": "取引を公開",
      "admin.title": "ニャンコサークル 管理",
      "admin.subtitle": "管理者のみアクセス可能。",
      "admin.auth_title": "管理者認証",
      "admin.placeholder_key": "ADMIN_KEY を入力",
      "admin.btn_load": "保存して読み込み",
      "admin.overview": "運営サマリー",
      "admin.metric_posts": "投稿",
      "admin.metric_comments": "コメント",
      "admin.metric_listings": "取引",
      "admin.manage_posts": "投稿管理",
      "admin.manage_comments": "コメント管理",
      "admin.manage_listings": "取引管理",
      "admin.btn_delete_post": "投稿を削除",
      "admin.btn_delete_comment": "コメントを削除",
      "admin.btn_delete_listing": "取引を削除",
      "doc.title": "システム可視化ドキュメント",
      "doc.back": "戻る",
      "doc.overview": "システム全体像",
      "doc.capabilities": "機能マップ",
      "doc.layers": "階層アーキテクチャ",
      "doc.api": "API モジュール",
      "doc.envelope": "統一レスポンス",
      "doc.security": "セキュリティ",
      "doc.mobile": "モバイル連携",
      "doc.mobile_strategy": "戦略",
      "doc.android_stack": "Android 技術スタック",
      "doc.roadmap": "ロードマップ",
      "common.delete": "削除",
      "common.edit": "編集",
      "common.no_items": "項目なし",
      "common.unknown": "不明",
      "common.no_description": "説明なし",
      "common.no_comments": "コメントはまだありません",
      "common.empty_posts_hint": "まだ投稿がありません。ログインしてコンソールから最初の投稿をしましょう。",
      "common.empty_listings": "取引情報はまだありません",
      "common.error_load_posts": "投稿の読み込みに失敗",
      "common.error_load_listings": "取引の読み込みに失敗",
      "common.confirm_delete_post": "この投稿を削除しますか？",
      "common.confirm_delete_listing": "この取引を削除しますか？",
      "alert.register_success": "登録しました！コンソールから最初のコンテンツを公開しましょう。",
      "alert.login_first": "先にログインしてください",
      "alert.login_to_comment": "コメントするにはログインが必要です",
      "meta.author": "投稿者",
      "meta.seller": "出品者",
      "meta.price": "価格",
      "meta.published_at": "投稿日時",
      "user.greeting": "こんにちは、{name}さん",
      "alert.publish_success": "公開しました！",
      "alert.update_success": "保存しました",
      "alert.draft_saved": "下書きを端末に保存しました",
      "common.empty_my_posts": "まだ投稿していません",
      "common.empty_my_listings": "まだ取引を出品していません",
      "meta.last_reply": "最新返信",
      "dashboard.stitch_zone": "Kitty Circle · 管理",
      "dashboard.stitch_brand": "Kitty Circle",
      "dashboard.stitch_subnav": "統一ナビ · 管理センター",
      "dashboard.stitch_admin_title": "管理センター",
      "dashboard.stitch_admin_sub": "Management Dashboard",
      "dashboard.create_new": "新規作成",
      "dashboard.nav_stitch_trades": "マイ取引",
      "dashboard.nav_stitch_profile": "プロフィール",
      "dashboard.nav_stitch_notif": "通知",
      "dashboard.nav_stitch_dm": "ダイレクトメッセージ",
      "dashboard.compose_post_title": "新規投稿",
      "dashboard.compose_post_sub": "日常・Q&A・イベントを共有",
      "dashboard.compose_listing_title": "取引を出す",
      "dashboard.compose_listing_sub": "左にメディア、右にタイトル・種類・価格・説明（Stitch レイアウト）",
      "dashboard.stitch_create_new": "新規作成",
      "dashboard.editing_badge": "編集中",
      "dashboard.cancel_edit": "編集をやめる",
      "form.save_draft": "下書き保存",
      "form.category_label": "カテゴリ",
      "form.media_block": "メディア",
      "form.drop_hint": "ここにドロップ、またはクリック",
      "form.drop_formats": "JPG / PNG / MP4 など",
      "form.tags_label": "タグ",
      "form.tag_add_placeholder": "タグを入力して Enter",
      "form.visibility": "公開範囲",
      "form.visibility_public": "公開 · ログインユーザー全員",
      "form.shortcut_hint": "下書きはこのブラウザ内のみ",
      "form.type_label": "種類",
      "form.listing_drop": "メディアをドロップ",
      "form.listing_media_hint": "高解像度 JPEG / PNG（サーバー上限に従います）",
      "form.stitch_price_amount": "価格",
      "form.stitch_price_minor_hint": "選択通貨の補助単位（分）で送信されます",
      "dashboard.nav_media": "メディア",
      "dashboard.nav_my_orders": "マイ注文",
      "media.upload_image": "画像アップロード (≤10MB)",
      "media.upload_video": "動画アップロード (≤200MB)",
      "media.btn_upload": "アップロード",
      "media.copy_id": "ID コピー",
      "media.stitch_sub": "アップロードした画像・動画を整理します。",
      "media.filter_all": "すべて",
      "media.filter_photos": "画像",
      "media.filter_videos": "動画",
      "media.empty": "メディアはまだありません",
      "media.attach_hint": "関連メディア ID (カンマ区切り)",
      "media.pick": "選択",
      "media.selected": "{n} 件選択中",
      "order.tab_buyer": "購入者として",
      "order.tab_seller": "出品者として",
      "order.btn_pay": "支払う",
      "order.btn_cancel": "キャンセル",
      "order.btn_ship": "発送",
      "order.btn_complete": "受取確認",
      "order.btn_refund": "返金",
      "order.col_listing": "商品",
      "order.col_amount": "金額",
      "order.col_status": "状態",
      "order.col_people": "買/売",
      "order.col_actions": "操作",
      "order.empty": "注文はありません",
      "order.status.pending_payment": "支払待ち",
      "order.status.paid": "支払済",
      "order.status.shipped": "発送済",
      "order.status.completed": "完了",
      "order.status.cancelled": "キャンセル",
      "order.status.refunded": "返金済",
      "order.stitch_title": "注文管理",
      "order.stitch_sub": "Stitch 準拠：集計・フィルタ・表・エクスポート",
      "order.export_csv": "CSV エクスポート",
      "order.filter_all": "すべて",
      "order.filter_pending": "未払",
      "order.filter_processing": "処理中",
      "order.filter_completed": "完了",
      "order.col_id": "注文 ID",
      "order.col_date": "日付",
      "order.col_total": "合計",
      "order.stitch_col_customer": "相手 / 取引",
      "order.stat_revenue": "取扱高",
      "order.stat_revenue_hint": "現在ロールの注文額",
      "order.stat_active": "アクティブ",
      "order.stat_avg": "平均注文",
      "order.stat_avg_hint": "表示中リストから",
      "order.stat_urgent_msg": "要対応 {n} 件",
      "order.stat_action": "要対応",
      "order.counterparty_id": "ユーザー {id}",
      "order.stitch_table_hint": "Stitch の表レイアウトに合わせた列",
      "order.stitch_sub2": "最近の販売の追跡・発送・管理。",
      "order.stat_revenue_bento": "総売上",
      "order.stat_active_bento": "アクティブ",
      "order.stat_satisfaction_bento": "顧客満足度",
      "order.stat_trend_na": "前期比は未接続",
      "order.stat_satisfaction_sub": "レビューは接続予定",
      "order.filter_all_orders": "すべて",
      "order.filter_options": "絞り込み",
      "order.col_customer": "相手",
      "order.footer_range": "1 – {m} 件 / 合計 {n} 件",
      "order.listing_fallback": "（商品名なし）",
      "order.empty_csv": "出力する行がありません",
      "form.btn_publish": "公開",
      "form.btn_publish_trade": "取引を公開",
      "form.stitch_title_ph": "タイトルを入力…",
      "form.stitch_content_ph": "本文…",
      "form.drop_hint_line1": "ここに画像/動画をドロップ",
      "form.browse_files": "参照",
      "form.stitch_cat_daily": "日常",
      "form.stitch_cat_tips": "お役立ち",
      "form.stitch_cat_questions": "Q&A",
      "form.stitch_cat_trade": "取引",
      "form.stitch_yuan_hint": "価格は内部で円分に変換",
      "form.stitch_price_yuan": "価格（元）",
      "form.format_title_bold": "太字",
      "form.format_title_italic": "斜体",
      "form.format_title_underline": "下線",
      "form.format_title_ul": "箇条書き",
      "form.format_title_ol": "番号付き",
      "form.format_title_align_outdent": "インデント減",
      "form.format_title_indent": "インデント増",
      "form.format_title_link": "リンク",
      "form.link_url_prompt": "リンク URL",
      "form.visibility_public_label": "公開",
      "form.visibility_public_desc": "ログインユーザーに表示",
      "dashboard.stitch_create_post": "新規投稿",
      "dashboard.stitch_listing_title": "取引の作成",
      "dashboard.header_brand": "Kitty Circle Admin",
      "dashboard.search_placeholder": "投稿・取引を検索…",
      "dashboard.search_placeholder_orders": "注文・商品を検索…",
      "dashboard.search_placeholder_posts": "タイトルや本文を検索…",
      "dashboard.search_placeholder_listings": "取引タイトルを検索…",
      "dashboard.search_placeholder_messages": "相手・メッセージを検索…",
      "dashboard.stitch_my_posts_title": "自分の投稿",
      "dashboard.stitch_my_posts_sub": "公開分と下書き",
      "dashboard.stitch_my_posts_sub2": "公開した内容の管理・確認。",
      "dashboard.posts_tab_all": "すべて",
      "dashboard.posts_filter_published": "公開済",
      "dashboard.posts_filter_drafts": "下書き",
      "dashboard.posts_stat_published": "公開 {n} 件",
      "dashboard.posts_stat_drafts": "下書き {n} 件",
      "dashboard.posts_stat_total_label": "投稿数",
      "dashboard.posts_stat_views_label": "表示回数",
      "dashboard.posts_views_na": "—",
      "dashboard.posts_load_more": "さらに読み込む",
      "dashboard.posts_all_loaded": "これ以上はありません",
      "dashboard.published_badge": "公開",
      "dashboard.draft_untitled": "無題の下書き",
      "dashboard.draft_badge": "下書き",
      "dashboard.draft_continue": "編集を続行",
      "notify.stitch_title": "通知",
      "notify.stitch_sub": "種別で絞り込み",
      "notify.cat_all": "すべて",
      "notify.categories_label": "カテゴリ",
      "profile.stitch_title": "プロフィール",
      "profile.stitch_sub": "Bento レイアウト、設定は端末内",
      "profile.pref_block": "設定",
      "profile.pref_compact": "コンパクト表示",
      "profile.pref_notify": "通知",
      "profile.btn_cancel": "戻る",
      "common.confirm_delete_draft": "下書きを削除？",
      "listing.btn_buy": "購入する",
      "report.btn": "通報",
      "report.placeholder": "通報理由",
      "report.submitted": "通報しました。ご協力ありがとうございます",
      "admin.nav_media": "メディア審査",
      "admin.nav_reports": "通報処理",
      "admin.nav_orders": "注文一覧",
      "admin.btn_approve": "承認",
      "admin.btn_reject": "拒否",
      "admin.btn_resolve": "処理して削除",
      "admin.btn_dismiss": "棄却",
      "nav.search_placeholder": "投稿・取引を検索…",
      "nav.compose": "投稿",
      "nav.notifications": "通知",
      "nav.settings": "設定",
      "nav.messages": "メッセージ",
      "stitch.tagline": "コミュニティ探索",
      "stitch.nav_home": "ホーム",
      "stitch.nav_discover": "発見",
      "stitch.nav_market": "マーケット",
      "stitch.nav_messages": "メッセージ",
      "stitch.nav_me": "マイページ",
      "stitch.search_posts": "猫の日常を検索…",
      "stitch.loading_more": "読み込み中…",
      "stitch.hot_topics": "話題",
      "stitch.rec_circles": "おすすめサークル",
      "stitch.view_all": "すべて",
      "stitch.join": "参加",
      "stitch.filter_follow_tip": "フォロー中のユーザーの投稿が表示されます。ログインしてください。",
      "stitch.filter_follow_login": "フォローを見るにはログイン",
      "stitch.like_login": "いいねにはログインが必要です",
      "stitch.follow": "フォロー",
      "stitch.following": "フォロー中",
      "stitch.follow_login": "フォローするにはログイン",
      "stitch.followed_ok": "フォローしました",
      "stitch.unfollowed_ok": "フォローを解除しました",
      "stitch.filter_rec": "おすすめ",
      "stitch.filter_new": "最新",
      "stitch.filter_follow": "フォロー",
      "stitch.post_detail": "投稿",
      "stitch.poster": "投稿者",
      "stitch.market_title": "マーケット",
      "stitch.market_heading": "マーケット",
      "stitch.market_lede": "譲渡・グッズ・サービスを一覧できます。",
      "stitch.price_negotiate": "要相談",
      "stitch.compose_title": "新規投稿",
      "stitch.compose_heading": "新規投稿",
      "stitch.compose_title_hint": "タイトルを付けると伸びやすいです",
      "stitch.compose_category": "カテゴリ",
      "stitch.discover_title": "発見",
      "stitch.discover_page_title": "サークル",
      "stitch.discover_search_ph": "サークルを検索...",
      "stitch.discover_tip": "サンプル表示です。後でデータ連携できます。",
      "stitch.chip_all": "すべて",
      "stitch.chip_newbie": "初心者",
      "stitch.chip_breed": "品種",
      "stitch.chip_gear": "グッズ",
      "stitch.chip_health": "健康",
      "stitch.circle_orange": "茶トラ同盟",
      "stitch.circle_orange_desc": "茶トラだいすき。",
      "stitch.circle_newbie": "初心者サポート",
      "stitch.circle_newbie_desc": "講座と Q&A。",
      "stitch.circle_black": "黒猫部",
      "stitch.circle_black_desc": "ミステリアスな子たち。",
      "stitch.circle_market": "お買い物",
      "stitch.circle_market_desc": "マーケットへ。",
      "stitch.messages_title": "メッセージ",
      "stitch.messages_tip": "DM と通知は管理画面でどうぞ。",
      "stitch.messages_cta": "管理画面へ",
      "stitch.profile_edit": "編集",
      "stitch.profile_share": "共有",
      "stitch.profile_share_ok": "リンクをコピーしました",
      "stitch.profile_title": "マイページ",
      "stitch.back_home": "ホームへ",
      "hero.title": "愛する家族の日常を、分かち合おう。",
      "hero.subtitle": "毎日のシェア、信頼できる取引、ペット主のワンストップコミュニティ——雑誌のように、丁寧に編まれています。",
      "hero.btn_primary": "シェアする",
      "hero.btn_secondary": "取引を見る",
      "hero.eyebrow": "コミュニティ · 配信中",
      "hero.index_primary_caption": "件の投稿が読まれ、話題になっています",
      "home.eyebrow_posts": "タイムライン · コミュニティ",
      "home.eyebrow_listings": "マーケット · 取引可能",
      "stat.posts": "投稿",
      "stat.listings": "取引",
      "stat.users": "ユーザー",
      "dashboard.nav_profile": "プロフィール",
      "dashboard.nav_notifications": "通知",
      "dashboard.nav_messages": "メッセージ",
      "profile.title": "プロフィール設定",
      "profile.nickname": "ニックネーム",
      "profile.avatar_url": "アバター URL（メディアをアップして URL をコピー）",
      "profile.bio": "自己紹介",
      "profile.btn_save": "保存",
      "profile.saved": "プロフィールを更新しました",
      "notify.empty": "通知はありません",
      "notify.mark_all_read": "すべて既読",
      "notify.badge_new": "新着",
      "notify.kind_comment": "コメント",
      "notify.kind_order": "注文",
      "notify.kind_report_handled": "通報",
      "notify.kind_message": "メッセージ",
      "notify.kind_system": "システム",
      "message.empty": "メッセージはありません",
      "message.placeholder": "メッセージを入力…",
      "message.btn_send": "送信",
      "message.start_new": "ユーザーにメッセージを送る",
      "message.target_user_id": "相手のユーザー ID",
      "message.filter_all": "すべて",
      "message.filter_unread": "未読",
      "message.filter_trades": "取引",
      "search.title": "検索結果",
      "search.placeholder": "キーワード",
      "search.btn": "検索",
      "search.no_result": "該当なし",
      "search.tab_all": "すべて",
      "search.tab_posts": "投稿",
      "search.tab_listings": "取引",
      "admin.nav_audit": "監査ログ",
      "admin.audit_empty": "監査記録なし",
      "admin.metric_users": "ユーザー",
      "admin.metric_orders": "注文",
      "admin.metric_media": "メディア",
      "admin.metric_reports": "通報",
      "payment.method": "支払方法",
    },
  };

  function getTheme() {
    const saved = localStorage.getItem(THEME_KEY);
    return saved && SUPPORTED_THEMES.some((t) => t.id === saved) ? saved : "light";
  }

  function getLang() {
    const saved = localStorage.getItem(LANG_KEY);
    if (saved && DICT[saved]) return saved;
    const nav = (navigator.language || "zh").toLowerCase();
    if (nav.startsWith("ja")) return "ja";
    if (nav.startsWith("en")) return "en";
    return "zh";
  }

  function setTheme(id) {
    localStorage.setItem(THEME_KEY, id);
    document.documentElement.setAttribute("data-theme", id);
  }

  function setLang(id) {
    localStorage.setItem(LANG_KEY, id);
    document.documentElement.lang = id;
    applyI18n();
  }

  function t(key) {
    const lang = getLang();
    const dict = DICT[lang] || DICT.zh;
    return dict[key] !== undefined ? dict[key] : key;
  }

  function applyI18n(root) {
    const scope = root || document;
    scope.querySelectorAll("[data-i18n]").forEach((el) => {
      el.textContent = t(el.getAttribute("data-i18n"));
    });
    scope.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
    });
    scope.querySelectorAll("[data-i18n-title]").forEach((el) => {
      el.setAttribute("title", t(el.getAttribute("data-i18n-title")));
    });

    const titleEl = document.querySelector("title[data-i18n]");
    if (titleEl) {
      document.title = t(titleEl.getAttribute("data-i18n"));
    }
  }

  function buildSettingsBar() {
    const bar = document.querySelector("#settings-bar");
    if (!bar) return;
    const lang = getLang();
    const theme = getTheme();

    const themeSelect = document.createElement("select");
    themeSelect.title = t("nav.settings_theme");
    themeSelect.setAttribute("aria-label", t("nav.settings_theme"));
    SUPPORTED_THEMES.forEach((item) => {
      const opt = document.createElement("option");
      opt.value = item.id;
      opt.textContent = item.label[lang] || item.label.zh;
      if (item.id === theme) opt.selected = true;
      themeSelect.appendChild(opt);
    });
    themeSelect.addEventListener("change", () => setTheme(themeSelect.value));

    const langSelect = document.createElement("select");
    langSelect.title = t("nav.settings_lang");
    langSelect.setAttribute("aria-label", t("nav.settings_lang"));
    SUPPORTED_LANGS.forEach((item) => {
      const opt = document.createElement("option");
      opt.value = item.id;
      opt.textContent = item.label;
      if (item.id === lang) opt.selected = true;
      langSelect.appendChild(opt);
    });
    langSelect.addEventListener("change", () => setLang(langSelect.value));

    bar.innerHTML = "";
    bar.classList.add("settings-bar");
    bar.appendChild(themeSelect);
    bar.appendChild(langSelect);
  }

  function toast(message, kind) {
    const tone = kind || "info";
    let stack = document.querySelector(".toast-stack");
    if (!stack) {
      stack = document.createElement("div");
      stack.className = "toast-stack";
      stack.setAttribute("aria-live", "polite");
      stack.setAttribute("aria-atomic", "false");
      document.body.appendChild(stack);
    }
    const item = document.createElement("div");
    item.className = `toast toast-${tone}`;
    if (tone === "error") {
      item.setAttribute("role", "alert");
    } else {
      item.setAttribute("role", "status");
    }
    item.textContent = String(message || "");
    stack.appendChild(item);

    requestAnimationFrame(() => item.classList.add("show"));
    const hide = () => {
      item.classList.remove("show");
      setTimeout(() => item.remove(), 220);
    };
    setTimeout(hide, 2600);
    item.addEventListener("click", hide, { once: true });
  }

  // Expose globally
  window.MeowShared = {
    t,
    getLang,
    getTheme,
    setTheme,
    setLang,
    applyI18n,
    buildSettingsBar,
    toast,
    SUPPORTED_THEMES,
    SUPPORTED_LANGS,
  };

  // Apply theme immediately (before paint)
  document.documentElement.setAttribute("data-theme", getTheme());
  document.documentElement.lang = getLang();

  document.addEventListener("DOMContentLoaded", () => {
    applyI18n();
    buildSettingsBar();
  });
})();
