(function () {
  const THEME_KEY = "meow_theme";
  const LANG_KEY = "meow_lang";

  const SUPPORTED_THEMES = [
    { id: "light", label: { zh: "浅色", en: "Light", ja: "ライト" } },
    { id: "dark", label: { zh: "深色", en: "Dark", ja: "ダーク" } },
    { id: "warm", label: { zh: "暖橙", en: "Warm", ja: "ウォーム" } },
  ];

  const SUPPORTED_LANGS = [
    { id: "zh", label: "简体中文" },
    { id: "en", label: "English" },
    { id: "ja", label: "日本語" },
  ];

  const DICT = {
    zh: {
      "app.title": "喵友圈",
      "app.subtitle": "猫咪与宠物主人的分享与交易社区",
      "nav.docs": "系统文档",
      "nav.dashboard": "我的管理中心",
      "nav.home": "返回前台",
      "nav.login": "登录 / 注册",
      "nav.logout": "退出",
      "nav.settings_theme": "主题",
      "nav.settings_lang": "语言",
      "auth.title": "登录 / 注册",
      "auth.tab_login": "登录",
      "auth.tab_register": "注册",
      "auth.placeholder_username": "用户名",
      "auth.placeholder_username_reg": "用户名 (≥3位)",
      "auth.placeholder_password": "密码",
      "auth.placeholder_password_reg": "密码 (≥6位)",
      "auth.placeholder_nickname": "昵称（可选）",
      "auth.btn_login": "登录",
      "auth.btn_register": "注册",
      "auth.tip": "登录后可进入管理中心发布帖子和交易信息。",
      "section.latest_posts": "最新帖子",
      "section.listings": "交易信息",
      "action.refresh": "刷新",
      "post.view_comments": "查看与评论",
      "post.placeholder_comment": "说点什么...",
      "post.btn_comment": "发表评论",
      "dashboard.title": "我的管理中心",
      "dashboard.subtitle": "发布帖子、发布交易、管理我的内容",
      "dashboard.not_login": "请先登录",
      "dashboard.not_login_tip": "管理中心仅登录用户可见。",
      "dashboard.go_home": "返回首页登录",
      "dashboard.nav_compose_post": "发布帖子",
      "dashboard.nav_compose_listing": "发布交易",
      "dashboard.nav_my_posts": "我的帖子",
      "dashboard.nav_my_listings": "我的交易",
      "form.title": "标题",
      "form.content": "写下你的日常分享...",
      "form.category_daily": "日常分享",
      "form.category_help": "求助问答",
      "form.category_activity": "线下活动",
      "form.category_trade": "交易信息",
      "form.tags": "标签，逗号分隔（如：橘猫,饮食）",
      "form.btn_publish_post": "发布帖子",
      "form.listing_title": "商品/服务标题",
      "form.listing_description": "描述信息",
      "form.type_product": "商品",
      "form.type_service": "服务",
      "form.type_adopt": "领养",
      "form.price": "价格（分），例如 9900",
      "form.currency": "币种",
      "form.btn_publish_listing": "发布交易",
      "admin.title": "喵友圈后台管理",
      "admin.subtitle": "仅管理员可访问操作接口（帖子/评论/交易治理）",
      "admin.auth_title": "管理员认证",
      "admin.placeholder_key": "输入 ADMIN_KEY",
      "admin.btn_load": "保存并加载数据",
      "admin.overview": "运营总览",
      "admin.metric_posts": "帖子",
      "admin.metric_comments": "评论",
      "admin.metric_listings": "交易",
      "admin.manage_posts": "帖子管理",
      "admin.manage_comments": "评论管理",
      "admin.manage_listings": "交易管理",
      "admin.btn_delete_post": "删除帖子",
      "admin.btn_delete_comment": "删除评论",
      "admin.btn_delete_listing": "删除交易",
      "doc.title": "喵友圈系统可视化文档",
      "doc.back": "返回业务页面",
      "doc.overview": "系统全景",
      "doc.capabilities": "能力地图",
      "doc.layers": "分层架构说明",
      "doc.api": "API 模块视图",
      "doc.envelope": "统一响应结构",
      "doc.security": "安全策略",
      "doc.mobile": "移动端接入策略",
      "doc.mobile_strategy": "建议策略",
      "doc.android_stack": "Android 推荐技术栈",
      "doc.roadmap": "演进路线图",
      "common.delete": "删除",
      "common.no_items": "暂无内容",
      "common.unknown": "未知",
      "common.no_description": "暂无描述",
      "common.no_comments": "暂时没有评论",
      "common.empty_posts_hint": "还没有帖子。登录后前往管理中心发布第一篇。",
      "common.empty_listings": "暂无交易信息",
      "common.error_load_posts": "加载帖子失败",
      "common.error_load_listings": "加载交易失败",
      "common.confirm_delete_post": "确认删除这条帖子吗？",
      "common.confirm_delete_listing": "确认删除这条交易吗？",
      "alert.register_success": "注册成功！前往管理中心发布第一条内容～",
      "alert.login_first": "请先登录",
      "alert.login_to_comment": "请先登录再评论",
      "meta.author": "作者",
      "meta.seller": "卖家",
      "meta.price": "价格",
      "meta.published_at": "发布于",
      "user.greeting": "你好，{name}",
      "alert.publish_success": "发布成功！",
      "common.empty_my_posts": "你还没有发布帖子",
      "common.empty_my_listings": "你还没有发布交易",
      "meta.last_reply": "最近回复",
      "dashboard.nav_media": "媒体库",
      "dashboard.nav_my_orders": "我的订单",
      "media.upload_image": "上传图片 (≤10MB)",
      "media.upload_video": "上传视频 (≤200MB，mp4/webm/mov)",
      "media.btn_upload": "上传",
      "media.copy_id": "复制 ID",
      "media.empty": "尚未上传媒体",
      "media.attach_hint": "可关联的媒体 ID (逗号分隔)",
      "media.pick": "选择",
      "media.selected": "已选 {n} 个",
      "order.tab_buyer": "我买的",
      "order.tab_seller": "我卖的",
      "order.btn_pay": "支付",
      "order.btn_cancel": "取消",
      "order.btn_ship": "发货",
      "order.btn_complete": "确认收货",
      "order.btn_refund": "退款",
      "order.empty": "暂无订单",
      "order.status.pending_payment": "待支付",
      "order.status.paid": "已支付",
      "order.status.shipped": "已发货",
      "order.status.completed": "已完成",
      "order.status.cancelled": "已取消",
      "order.status.refunded": "已退款",
      "listing.btn_buy": "立即购买",
      "report.btn": "举报",
      "report.placeholder": "请输入举报原因",
      "report.submitted": "已提交举报，感谢协助社区治理",
      "admin.nav_media": "媒体审核",
      "admin.nav_reports": "举报处理",
      "admin.nav_orders": "订单总览",
      "admin.btn_approve": "通过",
      "admin.btn_reject": "拒绝",
      "admin.btn_resolve": "处理并删除",
      "admin.btn_dismiss": "驳回",
      "nav.search_placeholder": "搜索帖子、交易...",
      "nav.notifications": "通知",
      "nav.messages": "私信",
      "hero.title": "把对毛孩子的爱，分享给同好",
      "hero.subtitle": "发布日常、交换经验、可信交易，一站式宠物主人社区",
      "hero.btn_primary": "开始分享",
      "hero.btn_secondary": "浏览交易",
      "stat.posts": "帖子",
      "stat.listings": "交易",
      "stat.users": "用户",
      "dashboard.nav_profile": "个人资料",
      "dashboard.nav_notifications": "通知中心",
      "dashboard.nav_messages": "私信",
      "profile.title": "资料设置",
      "profile.nickname": "昵称",
      "profile.avatar_url": "头像 URL（可上传媒体后复制其 URL）",
      "profile.bio": "个人简介",
      "profile.btn_save": "保存资料",
      "profile.saved": "资料已更新",
      "notify.empty": "暂无通知",
      "notify.mark_all_read": "全部标为已读",
      "notify.kind_comment": "新评论",
      "notify.kind_order": "订单状态",
      "notify.kind_report_handled": "举报处理",
      "notify.kind_message": "新私信",
      "notify.kind_system": "系统",
      "message.empty": "还没有私信",
      "message.placeholder": "输入消息...",
      "message.btn_send": "发送",
      "message.start_new": "给该用户发私信",
      "message.target_user_id": "对方用户 ID",
      "search.title": "搜索结果",
      "search.placeholder": "关键字",
      "search.btn": "搜索",
      "search.no_result": "没有找到匹配内容",
      "search.tab_all": "全部",
      "search.tab_posts": "帖子",
      "search.tab_listings": "交易",
      "admin.nav_audit": "审计日志",
      "admin.audit_empty": "暂无审计记录",
      "admin.metric_users": "用户",
      "admin.metric_orders": "订单",
      "admin.metric_media": "媒体",
      "admin.metric_reports": "举报",
      "payment.method": "支付方式",
    },
    en: {
      "app.title": "Meow Circle",
      "app.subtitle": "A community for cat & pet owners to share and trade",
      "nav.docs": "Docs",
      "nav.dashboard": "My Console",
      "nav.home": "Back to Site",
      "nav.login": "Sign in / Sign up",
      "nav.logout": "Logout",
      "nav.settings_theme": "Theme",
      "nav.settings_lang": "Language",
      "auth.title": "Sign in / Sign up",
      "auth.tab_login": "Sign in",
      "auth.tab_register": "Sign up",
      "auth.placeholder_username": "Username",
      "auth.placeholder_username_reg": "Username (min 3)",
      "auth.placeholder_password": "Password",
      "auth.placeholder_password_reg": "Password (min 6)",
      "auth.placeholder_nickname": "Nickname (optional)",
      "auth.btn_login": "Sign in",
      "auth.btn_register": "Sign up",
      "auth.tip": "After signing in, head to the console to publish posts and listings.",
      "section.latest_posts": "Latest Posts",
      "section.listings": "Listings",
      "action.refresh": "Refresh",
      "post.view_comments": "View & Comment",
      "post.placeholder_comment": "Say something...",
      "post.btn_comment": "Post Comment",
      "dashboard.title": "My Console",
      "dashboard.subtitle": "Publish posts and listings, manage my content",
      "dashboard.not_login": "Please sign in first",
      "dashboard.not_login_tip": "Console is only visible to signed-in users.",
      "dashboard.go_home": "Back to home to sign in",
      "dashboard.nav_compose_post": "New Post",
      "dashboard.nav_compose_listing": "New Listing",
      "dashboard.nav_my_posts": "My Posts",
      "dashboard.nav_my_listings": "My Listings",
      "form.title": "Title",
      "form.content": "Share your daily life...",
      "form.category_daily": "Daily Share",
      "form.category_help": "Q & A",
      "form.category_activity": "Activity",
      "form.category_trade": "Trade Info",
      "form.tags": "Tags, comma separated (e.g. cat,food)",
      "form.btn_publish_post": "Publish Post",
      "form.listing_title": "Product / Service Title",
      "form.listing_description": "Description",
      "form.type_product": "Product",
      "form.type_service": "Service",
      "form.type_adopt": "Adoption",
      "form.price": "Price in cents (e.g. 9900)",
      "form.currency": "Currency",
      "form.btn_publish_listing": "Publish Listing",
      "admin.title": "Meow Circle Admin",
      "admin.subtitle": "Only admins can access management APIs.",
      "admin.auth_title": "Admin Authentication",
      "admin.placeholder_key": "Enter ADMIN_KEY",
      "admin.btn_load": "Save & Load",
      "admin.overview": "Overview",
      "admin.metric_posts": "Posts",
      "admin.metric_comments": "Comments",
      "admin.metric_listings": "Listings",
      "admin.manage_posts": "Post Management",
      "admin.manage_comments": "Comment Management",
      "admin.manage_listings": "Listing Management",
      "admin.btn_delete_post": "Delete Post",
      "admin.btn_delete_comment": "Delete Comment",
      "admin.btn_delete_listing": "Delete Listing",
      "doc.title": "System Architecture Doc",
      "doc.back": "Back",
      "doc.overview": "System Overview",
      "doc.capabilities": "Capability Map",
      "doc.layers": "Layered Architecture",
      "doc.api": "API Modules",
      "doc.envelope": "Response Envelope",
      "doc.security": "Security",
      "doc.mobile": "Mobile Integration",
      "doc.mobile_strategy": "Strategy",
      "doc.android_stack": "Android Stack",
      "doc.roadmap": "Roadmap",
      "common.delete": "Delete",
      "common.no_items": "No items",
      "common.unknown": "unknown",
      "common.no_description": "No description",
      "common.no_comments": "No comments yet",
      "common.empty_posts_hint": "No posts yet. Sign in and head to the console to publish the first one.",
      "common.empty_listings": "No listings yet",
      "common.error_load_posts": "Failed to load posts",
      "common.error_load_listings": "Failed to load listings",
      "common.confirm_delete_post": "Delete this post?",
      "common.confirm_delete_listing": "Delete this listing?",
      "alert.register_success": "Signed up! Head to the console to publish your first content.",
      "alert.login_first": "Please sign in first",
      "alert.login_to_comment": "Please sign in to comment",
      "meta.author": "Author",
      "meta.seller": "Seller",
      "meta.price": "Price",
      "meta.published_at": "Posted at",
      "user.greeting": "Hi, {name}",
      "alert.publish_success": "Published!",
      "common.empty_my_posts": "You have not published any posts",
      "common.empty_my_listings": "You have not published any listings",
      "meta.last_reply": "Last reply",
      "dashboard.nav_media": "Media Library",
      "dashboard.nav_my_orders": "My Orders",
      "media.upload_image": "Upload image (≤10MB)",
      "media.upload_video": "Upload video (≤200MB, mp4/webm/mov)",
      "media.btn_upload": "Upload",
      "media.copy_id": "Copy ID",
      "media.empty": "No media uploaded",
      "media.attach_hint": "Attach media IDs (comma separated)",
      "media.pick": "Pick",
      "media.selected": "{n} selected",
      "order.tab_buyer": "As buyer",
      "order.tab_seller": "As seller",
      "order.btn_pay": "Pay",
      "order.btn_cancel": "Cancel",
      "order.btn_ship": "Ship",
      "order.btn_complete": "Confirm",
      "order.btn_refund": "Refund",
      "order.empty": "No orders",
      "order.status.pending_payment": "Pending payment",
      "order.status.paid": "Paid",
      "order.status.shipped": "Shipped",
      "order.status.completed": "Completed",
      "order.status.cancelled": "Cancelled",
      "order.status.refunded": "Refunded",
      "listing.btn_buy": "Buy now",
      "report.btn": "Report",
      "report.placeholder": "Reason for reporting",
      "report.submitted": "Report submitted, thanks for keeping the community healthy",
      "admin.nav_media": "Media Review",
      "admin.nav_reports": "Reports",
      "admin.nav_orders": "Orders",
      "admin.btn_approve": "Approve",
      "admin.btn_reject": "Reject",
      "admin.btn_resolve": "Resolve & delete",
      "admin.btn_dismiss": "Dismiss",
      "nav.search_placeholder": "Search posts, listings...",
      "nav.notifications": "Notifications",
      "nav.messages": "Messages",
      "hero.title": "Share the love for your furry family",
      "hero.subtitle": "Daily stories, trusted marketplace, one community for pet owners.",
      "hero.btn_primary": "Start sharing",
      "hero.btn_secondary": "Browse listings",
      "stat.posts": "Posts",
      "stat.listings": "Listings",
      "stat.users": "Members",
      "dashboard.nav_profile": "Profile",
      "dashboard.nav_notifications": "Inbox",
      "dashboard.nav_messages": "Messages",
      "profile.title": "Profile",
      "profile.nickname": "Nickname",
      "profile.avatar_url": "Avatar URL (upload to media then copy the URL)",
      "profile.bio": "About me",
      "profile.btn_save": "Save profile",
      "profile.saved": "Profile updated",
      "notify.empty": "No notifications",
      "notify.mark_all_read": "Mark all read",
      "notify.kind_comment": "Comment",
      "notify.kind_order": "Order",
      "notify.kind_report_handled": "Report",
      "notify.kind_message": "Message",
      "notify.kind_system": "System",
      "message.empty": "No messages",
      "message.placeholder": "Type a message...",
      "message.btn_send": "Send",
      "message.start_new": "Send a message to a user",
      "message.target_user_id": "Recipient user ID",
      "search.title": "Search results",
      "search.placeholder": "keyword",
      "search.btn": "Search",
      "search.no_result": "No matches",
      "search.tab_all": "All",
      "search.tab_posts": "Posts",
      "search.tab_listings": "Listings",
      "admin.nav_audit": "Audit Log",
      "admin.audit_empty": "No audit records",
      "admin.metric_users": "Users",
      "admin.metric_orders": "Orders",
      "admin.metric_media": "Media",
      "admin.metric_reports": "Reports",
      "payment.method": "Payment method",
    },
    ja: {
      "app.title": "ニャンコサークル",
      "app.subtitle": "猫とペットの飼い主のための共有・取引コミュニティ",
      "nav.docs": "ドキュメント",
      "nav.dashboard": "マイコンソール",
      "nav.home": "サイトへ戻る",
      "nav.login": "ログイン / 登録",
      "nav.logout": "ログアウト",
      "nav.settings_theme": "テーマ",
      "nav.settings_lang": "言語",
      "auth.title": "ログイン / 登録",
      "auth.tab_login": "ログイン",
      "auth.tab_register": "登録",
      "auth.placeholder_username": "ユーザー名",
      "auth.placeholder_username_reg": "ユーザー名（3文字以上）",
      "auth.placeholder_password": "パスワード",
      "auth.placeholder_password_reg": "パスワード（6文字以上）",
      "auth.placeholder_nickname": "ニックネーム（任意）",
      "auth.btn_login": "ログイン",
      "auth.btn_register": "登録",
      "auth.tip": "ログイン後、コンソールで投稿と取引を公開できます。",
      "section.latest_posts": "最新の投稿",
      "section.listings": "取引情報",
      "action.refresh": "更新",
      "post.view_comments": "コメントを見る",
      "post.placeholder_comment": "一言どうぞ...",
      "post.btn_comment": "コメント",
      "dashboard.title": "マイコンソール",
      "dashboard.subtitle": "投稿・取引の公開とコンテンツ管理",
      "dashboard.not_login": "ログインしてください",
      "dashboard.not_login_tip": "コンソールはログイン済みユーザー限定です。",
      "dashboard.go_home": "トップに戻ってログイン",
      "dashboard.nav_compose_post": "投稿を書く",
      "dashboard.nav_compose_listing": "取引を出す",
      "dashboard.nav_my_posts": "自分の投稿",
      "dashboard.nav_my_listings": "自分の取引",
      "form.title": "タイトル",
      "form.content": "日常をシェアしましょう...",
      "form.category_daily": "日常",
      "form.category_help": "相談",
      "form.category_activity": "イベント",
      "form.category_trade": "取引情報",
      "form.tags": "タグ、カンマ区切り",
      "form.btn_publish_post": "投稿する",
      "form.listing_title": "商品 / サービス名",
      "form.listing_description": "説明",
      "form.type_product": "商品",
      "form.type_service": "サービス",
      "form.type_adopt": "里親",
      "form.price": "価格（単位: 分, 例: 9900）",
      "form.currency": "通貨",
      "form.btn_publish_listing": "取引を公開",
      "admin.title": "ニャンコサークル 管理",
      "admin.subtitle": "管理者のみアクセス可能。",
      "admin.auth_title": "管理者認証",
      "admin.placeholder_key": "ADMIN_KEY を入力",
      "admin.btn_load": "保存して読み込み",
      "admin.overview": "運営サマリー",
      "admin.metric_posts": "投稿",
      "admin.metric_comments": "コメント",
      "admin.metric_listings": "取引",
      "admin.manage_posts": "投稿管理",
      "admin.manage_comments": "コメント管理",
      "admin.manage_listings": "取引管理",
      "admin.btn_delete_post": "投稿を削除",
      "admin.btn_delete_comment": "コメントを削除",
      "admin.btn_delete_listing": "取引を削除",
      "doc.title": "システム可視化ドキュメント",
      "doc.back": "戻る",
      "doc.overview": "システム全体像",
      "doc.capabilities": "機能マップ",
      "doc.layers": "階層アーキテクチャ",
      "doc.api": "API モジュール",
      "doc.envelope": "統一レスポンス",
      "doc.security": "セキュリティ",
      "doc.mobile": "モバイル連携",
      "doc.mobile_strategy": "戦略",
      "doc.android_stack": "Android 技術スタック",
      "doc.roadmap": "ロードマップ",
      "common.delete": "削除",
      "common.no_items": "項目なし",
      "common.unknown": "不明",
      "common.no_description": "説明なし",
      "common.no_comments": "コメントはまだありません",
      "common.empty_posts_hint": "まだ投稿がありません。ログインしてコンソールから最初の投稿をしましょう。",
      "common.empty_listings": "取引情報はまだありません",
      "common.error_load_posts": "投稿の読み込みに失敗",
      "common.error_load_listings": "取引の読み込みに失敗",
      "common.confirm_delete_post": "この投稿を削除しますか？",
      "common.confirm_delete_listing": "この取引を削除しますか？",
      "alert.register_success": "登録しました！コンソールから最初のコンテンツを公開しましょう。",
      "alert.login_first": "先にログインしてください",
      "alert.login_to_comment": "コメントするにはログインが必要です",
      "meta.author": "投稿者",
      "meta.seller": "出品者",
      "meta.price": "価格",
      "meta.published_at": "投稿日時",
      "user.greeting": "こんにちは、{name}さん",
      "alert.publish_success": "公開しました！",
      "common.empty_my_posts": "まだ投稿していません",
      "common.empty_my_listings": "まだ取引を出品していません",
      "meta.last_reply": "最新返信",
      "dashboard.nav_media": "メディア",
      "dashboard.nav_my_orders": "マイ注文",
      "media.upload_image": "画像アップロード (≤10MB)",
      "media.upload_video": "動画アップロード (≤200MB)",
      "media.btn_upload": "アップロード",
      "media.copy_id": "ID コピー",
      "media.empty": "メディアはまだありません",
      "media.attach_hint": "関連メディア ID (カンマ区切り)",
      "media.pick": "選択",
      "media.selected": "{n} 件選択中",
      "order.tab_buyer": "購入者として",
      "order.tab_seller": "出品者として",
      "order.btn_pay": "支払う",
      "order.btn_cancel": "キャンセル",
      "order.btn_ship": "発送",
      "order.btn_complete": "受取確認",
      "order.btn_refund": "返金",
      "order.empty": "注文はありません",
      "order.status.pending_payment": "支払待ち",
      "order.status.paid": "支払済",
      "order.status.shipped": "発送済",
      "order.status.completed": "完了",
      "order.status.cancelled": "キャンセル",
      "order.status.refunded": "返金済",
      "listing.btn_buy": "購入する",
      "report.btn": "通報",
      "report.placeholder": "通報理由",
      "report.submitted": "通報しました。ご協力ありがとうございます",
      "admin.nav_media": "メディア審査",
      "admin.nav_reports": "通報処理",
      "admin.nav_orders": "注文一覧",
      "admin.btn_approve": "承認",
      "admin.btn_reject": "拒否",
      "admin.btn_resolve": "処理して削除",
      "admin.btn_dismiss": "棄却",
      "nav.search_placeholder": "投稿・取引を検索…",
      "nav.notifications": "通知",
      "nav.messages": "メッセージ",
      "hero.title": "愛する家族の日常を分かち合おう",
      "hero.subtitle": "毎日のシェア、信頼できる取引。ペットオーナーのワンストップコミュニティ。",
      "hero.btn_primary": "シェアする",
      "hero.btn_secondary": "取引を見る",
      "stat.posts": "投稿",
      "stat.listings": "取引",
      "stat.users": "ユーザー",
      "dashboard.nav_profile": "プロフィール",
      "dashboard.nav_notifications": "通知",
      "dashboard.nav_messages": "メッセージ",
      "profile.title": "プロフィール設定",
      "profile.nickname": "ニックネーム",
      "profile.avatar_url": "アバター URL（メディアをアップして URL をコピー）",
      "profile.bio": "自己紹介",
      "profile.btn_save": "保存",
      "profile.saved": "プロフィールを更新しました",
      "notify.empty": "通知はありません",
      "notify.mark_all_read": "すべて既読",
      "notify.kind_comment": "コメント",
      "notify.kind_order": "注文",
      "notify.kind_report_handled": "通報",
      "notify.kind_message": "メッセージ",
      "notify.kind_system": "システム",
      "message.empty": "メッセージはありません",
      "message.placeholder": "メッセージを入力…",
      "message.btn_send": "送信",
      "message.start_new": "ユーザーにメッセージを送る",
      "message.target_user_id": "相手のユーザー ID",
      "search.title": "検索結果",
      "search.placeholder": "キーワード",
      "search.btn": "検索",
      "search.no_result": "該当なし",
      "search.tab_all": "すべて",
      "search.tab_posts": "投稿",
      "search.tab_listings": "取引",
      "admin.nav_audit": "監査ログ",
      "admin.audit_empty": "監査記録なし",
      "admin.metric_users": "ユーザー",
      "admin.metric_orders": "注文",
      "admin.metric_media": "メディア",
      "admin.metric_reports": "通報",
      "payment.method": "支払方法",
    },
  };

  function getTheme() {
    const saved = localStorage.getItem(THEME_KEY);
    return saved && SUPPORTED_THEMES.some((t) => t.id === saved) ? saved : "light";
  }

  function getLang() {
    const saved = localStorage.getItem(LANG_KEY);
    if (saved && DICT[saved]) return saved;
    const nav = (navigator.language || "zh").toLowerCase();
    if (nav.startsWith("ja")) return "ja";
    if (nav.startsWith("en")) return "en";
    return "zh";
  }

  function setTheme(id) {
    localStorage.setItem(THEME_KEY, id);
    document.documentElement.setAttribute("data-theme", id);
  }

  function setLang(id) {
    localStorage.setItem(LANG_KEY, id);
    document.documentElement.lang = id;
    applyI18n();
  }

  function t(key) {
    const lang = getLang();
    const dict = DICT[lang] || DICT.zh;
    return dict[key] !== undefined ? dict[key] : key;
  }

  function applyI18n(root) {
    const scope = root || document;
    scope.querySelectorAll("[data-i18n]").forEach((el) => {
      el.textContent = t(el.getAttribute("data-i18n"));
    });
    scope.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
    });
    scope.querySelectorAll("[data-i18n-title]").forEach((el) => {
      el.setAttribute("title", t(el.getAttribute("data-i18n-title")));
    });

    const titleEl = document.querySelector("title[data-i18n]");
    if (titleEl) {
      document.title = t(titleEl.getAttribute("data-i18n"));
    }
  }

  function buildSettingsBar() {
    const bar = document.querySelector("#settings-bar");
    if (!bar) return;
    const lang = getLang();
    const theme = getTheme();

    const themeSelect = document.createElement("select");
    themeSelect.title = t("nav.settings_theme");
    themeSelect.setAttribute("aria-label", t("nav.settings_theme"));
    SUPPORTED_THEMES.forEach((item) => {
      const opt = document.createElement("option");
      opt.value = item.id;
      opt.textContent = item.label[lang] || item.label.zh;
      if (item.id === theme) opt.selected = true;
      themeSelect.appendChild(opt);
    });
    themeSelect.addEventListener("change", () => setTheme(themeSelect.value));

    const langSelect = document.createElement("select");
    langSelect.title = t("nav.settings_lang");
    langSelect.setAttribute("aria-label", t("nav.settings_lang"));
    SUPPORTED_LANGS.forEach((item) => {
      const opt = document.createElement("option");
      opt.value = item.id;
      opt.textContent = item.label;
      if (item.id === lang) opt.selected = true;
      langSelect.appendChild(opt);
    });
    langSelect.addEventListener("change", () => setLang(langSelect.value));

    bar.innerHTML = "";
    bar.classList.add("settings-bar");
    bar.appendChild(themeSelect);
    bar.appendChild(langSelect);
  }

  // Expose globally
  window.MeowShared = {
    t,
    getLang,
    getTheme,
    setTheme,
    setLang,
    applyI18n,
    buildSettingsBar,
    SUPPORTED_THEMES,
    SUPPORTED_LANGS,
  };

  // Apply theme immediately (before paint)
  document.documentElement.setAttribute("data-theme", getTheme());
  document.documentElement.lang = getLang();

  document.addEventListener("DOMContentLoaded", () => {
    applyI18n();
    buildSettingsBar();
  });
})();
