/* M&D cute theme — must load after Tailwind CDN script. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "var(--brand-weak)",
        "tertiary-fixed": "var(--ok-bg)",
        "surface-container-highest": "var(--surface-500)",
        secondary: "var(--accent)",
        "primary-fixed": "var(--surface-300)",
        "on-surface-variant": "var(--muted)",
        "surface-variant": "var(--surface-400)",
        "inverse-on-surface": "var(--bg)",
        "surface-container-low": "var(--surface-300)",
        "surface-container": "var(--panel)",
        "on-tertiary-fixed-variant": "var(--ok)",
        "on-error": "var(--text-invert)",
        primary: "var(--brand-strong)",
        "surface-container-lowest": "var(--card)",
        "secondary-container": "var(--accent-weak)",
        "outline-variant": "var(--border)",
        "on-tertiary-container": "var(--ok)",
        "on-surface": "var(--text)",
        "on-tertiary": "var(--text-invert)",
        "on-secondary": "var(--text-invert)",
        "tertiary-fixed-dim": "var(--ok-bg)",
        "secondary-fixed-dim": "var(--accent-weak)",
        "on-background": "var(--text)",
        outline: "var(--border-medium)",
        "on-tertiary-fixed": "var(--ok)",
        "on-primary": "var(--text-invert)",
        "error-container": "var(--danger-bg)",
        "inverse-primary": "var(--brand-weak)",
        "surface-tint": "var(--brand)",
        "on-secondary-fixed": "var(--text)",
        error: "var(--danger)",
        "on-primary-fixed-variant": "var(--brand-text)",
        "inverse-surface": "var(--text)",
        "tertiary-container": "var(--ok-bg)",
        "primary-container": "var(--brand)",
        "on-primary-container": "var(--brand-text)",
        "surface-bright": "var(--surface-100)",
        background: "var(--bg)",
        surface: "var(--card)",
        "secondary-fixed": "var(--accent-weak)",
        "on-secondary-fixed-variant": "var(--text)",
        "on-error-container": "var(--danger)",
        "on-primary-fixed": "var(--brand-text)",
        tertiary: "var(--ok)",
        "surface-dim": "var(--surface-400)",
        "on-secondary-container": "var(--text)",
        "surface-container-high": "var(--surface-400)",
      },
      borderRadius: {
        DEFAULT: "8px",
        lg: "8px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "8px",
        lg: "24px",
        xl: "32px",
        "card-gap": "12px",
        "container-padding": "16px",
        base: "4px",
        sm: "12px",
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["28px", { lineHeight: "36px", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
      },
    },
  },
};
