/* M&D Stitch V2 Tailwind bridge. Load after Tailwind CDN and after theme CSS. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--bg)",
        surface: "var(--card)",
        primary: "var(--brand)",
        secondary: "var(--secondary)",
        tertiary: "var(--accent)",
        error: "var(--danger)",
        outline: "var(--border-medium)",
        "outline-variant": "var(--border)",
        "on-background": "var(--text)",
        "on-surface": "var(--text)",
        "on-surface-variant": "var(--muted)",
        "on-primary": "var(--text-invert)",
        "on-secondary": "var(--text)",
        "on-tertiary": "var(--text-invert)",
        "on-error": "var(--text-invert)",
        "primary-container": "var(--brand)",
        "on-primary-container": "var(--brand-text)",
        "primary-fixed": "var(--surface-300)",
        "primary-fixed-dim": "var(--brand-weak)",
        "on-primary-fixed": "var(--brand-text)",
        "on-primary-fixed-variant": "var(--brand-text)",
        "secondary-container": "var(--accent-weak)",
        "secondary-fixed": "var(--accent-weak)",
        "secondary-fixed-dim": "var(--accent-weak)",
        "on-secondary-container": "var(--text)",
        "on-secondary-fixed": "var(--text)",
        "on-secondary-fixed-variant": "var(--text)",
        "tertiary-container": "var(--ok-bg)",
        "tertiary-fixed": "var(--ok-bg)",
        "tertiary-fixed-dim": "var(--ok-bg)",
        "on-tertiary-container": "var(--ok)",
        "on-tertiary-fixed": "var(--ok)",
        "on-tertiary-fixed-variant": "var(--ok)",
        "error-container": "var(--danger-bg)",
        "on-error-container": "var(--danger)",
        "inverse-surface": "var(--text)",
        "inverse-on-surface": "var(--bg)",
        "inverse-primary": "var(--brand-weak)",
        "surface-tint": "var(--brand)",
        "surface-bright": "var(--surface-100)",
        "surface-dim": "var(--surface-400)",
        "surface-variant": "var(--surface-400)",
        "surface-container-lowest": "var(--card)",
        "surface-container-low": "var(--surface-300)",
        "surface-container": "var(--panel)",
        "surface-container-high": "var(--surface-400)",
        "surface-container-highest": "var(--surface-500)",
      },
      borderRadius: {
        DEFAULT: "12px",
        lg: "16px",
        xl: "20px",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "card-gap": "12px",
        "container-padding": "16px",
      },
      fontFamily: {
        "headline-xl": ["Outfit", "Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Outfit", "Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-md": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "1.12", letterSpacing: "0", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
      },
    },
  },
};
