/* Dopamine Petal theme — must load after Tailwind CDN script. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb2b9",
        "tertiary-fixed": "#75f9d1",
        "surface-container-highest": "#e4e2dd",
        secondary: "#805600",
        "primary-fixed": "#ffdadc",
        "on-surface-variant": "#594042",
        "surface-variant": "#e4e2dd",
        "inverse-on-surface": "#f2f1ec",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "on-tertiary-fixed-variant": "#00513f",
        "on-error": "#ffffff",
        primary: "#b52044",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fdaf18",
        "outline-variant": "#e1bec0",
        "on-tertiary-container": "#003528",
        "on-surface": "#1b1c19",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#55dcb6",
        "secondary-fixed-dim": "#ffba46",
        "on-background": "#1b1c19",
        outline: "#8d7072",
        "on-tertiary-fixed": "#002118",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#ffb2b9",
        "surface-tint": "#b52044",
        "on-secondary-fixed": "#281800",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#91002f",
        "inverse-surface": "#30312e",
        "tertiary-container": "#00a986",
        "primary-container": "#ff5a77",
        "on-primary-container": "#62001d",
        "surface-bright": "#fbf9f4",
        background: "#fbf9f4",
        surface: "#fbf9f4",
        "secondary-fixed": "#ffddb0",
        "on-secondary-fixed-variant": "#614000",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#400010",
        tertiary: "#006b54",
        "surface-dim": "#dbdad5",
        "on-secondary-container": "#694600",
        "surface-container-high": "#eae8e3",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "8px",
        lg: "24px",
        xl: "32px",
        "card-gap": "12px",
        "container-padding": "16px",
        base: "4px",
        sm: "12px",
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["28px", { lineHeight: "36px", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
      },
    },
  },
};
